(function(g){var window=this;'use strict';var hPa=function(a,b){return g.Ob(a,b)},iPa=function(a,b){b=b instanceof g.Hc?b:g.Nc(b,/^data:image\//i.test(b));
a.src=g.Ic(b)},jPa=function(a){if(a instanceof g.Vh)return a;
if("function"==typeof a.Eg)return a.Eg(!1);if(g.La(a)){var b=0,c=new g.Vh;c.i=function(){for(;;){if(b>=a.length)throw g.ai;if(b in a)return a[b++];b++}};
c.next=c.i.bind(c);return c}throw Error("Not implemented");},kPa=function(a,b,c){if(g.La(a))try{g.Bb(a,b,c)}catch(d){if(d!==g.ai)throw d;
}else{a=jPa(a);try{for(;;)b.call(c,a.next(),void 0,a)}catch(d){if(d!==g.ai)throw d;}}},B6=function(a){g.kk(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.Ra()).toString(36));
return a},C6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.vk(a.l,b,c)},lPa=function(a,b){var c=[];
kPa(b,function(d){try{var e=g.jr.prototype.l.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.ir(e)&&c.push(d)},a);
return c},mPa=function(a,b){lPa(a,b).forEach(function(c){g.jr.prototype.remove.call(this,c)},a)},nPa=function(a){if(a.V){if(a.V.locationOverrideToken)return{locationOverrideToken:a.V.locationOverrideToken};
if(null!=a.V.latitudeE7&&null!=a.V.longitudeE7)return{latitudeE7:a.V.latitudeE7,longitudeE7:a.V.longitudeE7}}return null},oPa=function(a,b){g.ib(a,b)||a.push(b)},D6=function(a){var b=0,c;
for(c in a)b++;return b},pPa=function(a){try{return g.A.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},E6=function(a){if(g.A.JSON)try{return g.A.JSON.parse(a)}catch(b){}return pPa(a)},qPa=function(a,b,c,d){var e=new g.ck(null,void 0);
a&&g.dk(e,a);b&&g.ek(e,b);c&&g.fk(e,c);d&&(e.J=d);return e},F6=function(a,b){g.Gu[a]=!0;
var c=g.Eu();c&&c.publish.apply(c,arguments);g.Gu[a]=!1},G6=function(a){this.name=this.id="";
this.clientName="UNKNOWN_INTERFACE";this.app="";this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.ci;this.model=this.brand="";this.year=0;this.chipset=this.osVersion=this.os="";a&&(this.id=a.id||a.name,this.name=a.name,this.clientName=a.clientName||"UNKNOWN_INTERFACE",this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||
"",this.theme=a.theme||"u",rPa(this,a.capabilities||""),sPa(this,a.experiments||""),this.brand=a.brand||"",this.model=a.model||"",this.year=a.year||0,this.os=a.os||"",this.osVersion=a.osVersion||"",this.chipset=a.chipset||"")},rPa=function(a,b){a.capabilities.clear();
g.Ro(b.split(","),g.Pa(hPa,tPa)).forEach(function(c){a.capabilities.add(c)})},sPa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},H6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||"";this.idType=a.screenIdType||"normal"},I6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},uPa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid,screenIdType:a.idType}},vPa=function(a){return new H6(a)},wPa=function(a){return Array.isArray(a)?g.Re(a,vPa):[]},J6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+((a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+",idType:"+a.idType+"}"):"null"},K6=function(a){return Array.isArray(a)?"["+g.Re(a,J6).join(",")+"]":"null"},L6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},xPa=function(a){return g.Re(a,function(b){return{key:b.id,
name:b.name}})},M6=function(a,b){return g.eb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},N6=function(a,b){return g.eb(a,function(c){return I6(c,b)})},yPa=function(){var a=(0,g.dz)();
a&&mPa(a,a.i.Eg(!0))},O6=function(){var a=g.gz("yt-remote-connected-devices")||[];
g.yb(a);return a},zPa=function(a){if(g.jb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Re(a,function(d,e){return 0==e?d:d.substring(c.length)})},APa=function(a){g.fz("yt-remote-connected-devices",a,86400)},Q6=function(){if(P6)return P6;
var a=g.gz("yt-remote-device-id");a||(a=L6(),g.fz("yt-remote-device-id",a,31536E3));for(var b=O6(),c=1,d=a;g.ib(b,d);)c++,d=a+"#"+c;return P6=d},R6=function(){var a=O6(),b=Q6();
g.ib(a,b);g.jz()&&g.Ab(a,b);a=zPa(a);if(g.jb(a))try{g.nt("remote_sid")}catch(c){}else try{g.lt("remote_sid",a.join(","),-1)}catch(c){}},BPa=function(){return g.gz("yt-remote-session-browser-channel")},CPa=function(){return g.gz("yt-remote-local-screens")||[]},DPa=function(){g.fz("yt-remote-lounge-token-expiration",!0,86400)},EPa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Re(CPa(),function(d){return d.loungeToken}),c=g.Re(a,function(d){return d.loungeToken});
g.Am(c,function(d){return!g.ib(b,d)})&&DPa();
g.fz("yt-remote-local-screens",a,31536E3)},FPa=function(a,b){g.fz("yt-remote-session-browser-channel",a);
g.fz("yt-remote-session-screen-id",b);a=O6();b=Q6();g.ib(a,b)||a.push(b);APa(a);R6()},S6=function(a){a||(g.iz("yt-remote-session-screen-id"),g.iz("yt-remote-session-video-id"));
R6();a=O6();g.nb(a,Q6());APa(a)},GPa=function(){if(!T6){var a=g.tr();
a&&(T6=new g.dr(a))}},HPa=function(){GPa();
return T6?!!T6.get("yt-remote-use-staging-server"):!1},U6=function(){var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);
return a?parseInt(a[1],10):0},IPa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},JPa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},V6=function(a){a.length?KPa(a.shift(),function(){V6(a)}):W6()},LPa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},KPa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.Cj(d,g.zl(a));(document.head||document.documentElement).appendChild(d)},MPa=function(){var a=U6(),b=[];
if(1<a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}return b},W6=function(){var a=JPa();
a&&a(!1,"No cast extension found")},X6=function(){if(NPa){var a=2,b=JPa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;KPa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",W6,c)}},OPa=function(){X6();
var a=MPa();a.push("//www.gstatic.com/eureka/clank/cast_sender.js");V6(a)},QPa=function(){X6();
var a=MPa();a.push.apply(a,g.la(PPa.map(LPa)));a.push("//www.gstatic.com/eureka/clank/cast_sender.js");V6(a)},Y6=function(a,b,c){g.E.call(this);
this.I=null!=c?(0,g.C)(a,c):a;this.Mf=b;this.C=(0,g.C)(this.yO,this);this.i=!1;this.l=0;this.u=this.Ib=null;this.B=[]},Z6=function(a,b,c){g.E.call(this);
this.B=null!=c?a.bind(c):a;this.Mf=b;this.u=null;this.i=!1;this.l=0;this.Ib=null},$6=function(a){a.Ib=g.lh(function(){a.Ib=null;
a.i&&!a.l&&(a.i=!1,$6(a))},a.Mf);
var b=a.u;a.u=null;a.B.apply(null,b)},a7=function(){},b7=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.A.setTimeout(function(){a()},b)},d7=function(a){c7.dispatchEvent(new RPa(c7,a))},RPa=function(a,b){g.lf.call(this,"statevent",a);
this.stat=b},e7=function(a,b,c,d){this.i=a;
this.l=b;this.L=c;this.J=d||1;this.C=45E3;this.B=new g.wk(this);this.u=new g.kh;this.u.setInterval(250)},TPa=function(a,b,c){a.Ds=1;
a.xm=B6(b.clone());a.Up=c;a.I=!0;SPa(a,null)},f7=function(a,b,c,d,e){a.Ds=1;
a.xm=B6(b.clone());a.Up=null;a.I=c;e&&(a.EL=!1);SPa(a,d)},SPa=function(a,b){a.ls=Date.now();
g7(a);a.Mn=a.xm.clone();C6(a.Mn,"t",a.J);a.pw=0;a.We=a.i.SB(a.i.Tv()?b:null);0<a.KA&&(a.jz=new Z6((0,g.C)(a.DM,a,a.We),a.KA));a.B.Pa(a.We,"readystatechange",a.zO);b=a.Co?g.Vb(a.Co):{};a.Up?(a.Wz="POST",b["Content-Type"]="application/x-www-form-urlencoded",a.We.send(a.Mn,a.Wz,a.Up,b)):(a.Wz="GET",a.EL&&!g.kg&&(b.Connection="close"),a.We.send(a.Mn,a.Wz,null,b));a.i.lj(1)},WPa=function(a,b,c){for(var d=!0;!a.Oo&&a.pw<c.length;){var e=UPa(a,c);
if(e==h7){4==b&&(a.pm=4,d7(15),d=!1);break}else if(e==VPa){a.pm=4;d7(16);d=!1;break}else i7(a,e)}4==b&&0==c.length&&(a.pm=1,d7(17),d=!1);a.xj=a.xj&&d;d||(j7(a),k7(a))},UPa=function(a,b){var c=a.pw,d=b.indexOf("\n",c);
if(-1==d)return h7;c=Number(b.substring(c,d));if(isNaN(c))return VPa;d+=1;if(d+c>b.length)return h7;b=b.substr(d,c);a.pw=d+c;return b},YPa=function(a,b){a.ls=Date.now();
g7(a);var c=b?window.location.hostname:"";a.Mn=a.xm.clone();g.kk(a.Mn,"DOMAIN",c);g.kk(a.Mn,"t",a.J);try{a.Bj=new ActiveXObject("htmlfile")}catch(m){j7(a);a.pm=7;d7(22);k7(a);return}var d="<html><body>";if(b){var e="";for(b=0;b<c.length;b++){var f=c.charAt(b);if("<"==f)f=e+"\\x3c";else if(">"==f)f=e+"\\x3e";else{if(f in l7)f=l7[f];else if(f in XPa)f=l7[f]=XPa[f];else{var h=f.charCodeAt(0);if(31<h&&127>h)var l=f;else{if(256>h){if(l="\\x",16>h||256<h)l+="0"}else l="\\u",4096>h&&(l+="0");l+=h.toString(16).toUpperCase()}f=
l7[f]=l}f=e+f}e=f}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.hd(g.hc("b/12014412"),d);a.Bj.open();a.Bj.write(g.dd(c));a.Bj.close();a.Bj.parentWindow.m=(0,g.C)(a.KU,a);a.Bj.parentWindow.d=(0,g.C)(a.UK,a,!0);a.Bj.parentWindow.rpcClose=(0,g.C)(a.UK,a,!1);c=a.Bj.createElement("DIV");a.Bj.parentWindow.document.body.appendChild(c);d=g.Mc(a.Mn.toString());d=g.ud(g.Ic(d));d=g.hd(g.hc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.nd(c,d);a.i.lj(1)},g7=function(a){a.qF=Date.now()+
a.C;
ZPa(a,a.C)},ZPa=function(a,b){if(null!=a.Ks)throw Error("WatchDog timer not null");
a.Ks=b7((0,g.C)(a.SU,a),b)},m7=function(a){a.Ks&&(g.A.clearTimeout(a.Ks),a.Ks=null)},k7=function(a){a.i.df()||a.Oo||a.i.Fw(a)},j7=function(a){m7(a);
g.ff(a.jz);a.jz=null;a.u.stop();g.yk(a.B);if(a.We){var b=a.We;a.We=null;b.abort();b.dispose()}a.Bj&&(a.Bj=null)},i7=function(a,b){try{a.i.NK(a,b),a.i.lj(4)}catch(c){}},aQa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;$Pa(a,b,function(h){h?c(!0):g.A.setTimeout(function(){aQa(a,b,c,d,f)},f)})}},$Pa=function(a,b,c){var d=new Image;
d.onload=function(){try{n7(d),c(!0)}catch(e){}};
d.onerror=function(){try{n7(d),c(!1)}catch(e){}};
d.onabort=function(){try{n7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{n7(d),c(!1)}catch(e){}};
g.A.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
iPa(d,a)},n7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},bQa=function(a){this.i=a;
this.l=new a7},cQa=function(a){var b=o7(a.i,a.Ft,"/mail/images/cleardot.gif");
B6(b);aQa(b.toString(),5E3,(0,g.C)(a.sP,a),3,2E3);a.lj(1)},q7=function(a){var b=a.i.L;
if(null!=b)d7(5),b?(d7(11),p7(a.i,a,!1)):(d7(12),p7(a.i,a,!0));else if(a.eh=new e7(a,void 0,void 0,void 0),a.eh.Co=a.LA,b=a.i,b=o7(b,b.Tv()?a.qt:null,a.MA),d7(5),!g.fe||g.$d(10))C6(b,"TYPE","xmlhttp"),f7(a.eh,b,!1,a.qt,!1);else{C6(b,"TYPE","html");var c=a.eh;a=!!a.qt;c.Ds=3;c.xm=B6(b.clone());YPa(c,a)}},r7=function(a,b,c){this.Oa=1;
this.i=[];this.u=[];this.B=new a7;this.J=a||null;this.L=null!=b?b:null;this.C=c||!1},dQa=function(a,b){this.i=a;
this.map=b;this.context=null},eQa=function(a,b,c,d){g.lf.call(this,"timingevent",a);
this.size=b;this.Nv=d},fQa=function(a){g.lf.call(this,"serverreachability",a)},iQa=function(a){gQa(a);
if(3==a.Oa){var b=a.Xu++,c=a.ix.clone();g.kk(c,"SID",a.l);g.kk(c,"RID",b);g.kk(c,"TYPE","terminate");s7(a,c);b=new e7(a,a.l,b,void 0);b.Ds=2;b.xm=B6(c.clone());iPa(new Image,b.xm.toString());b.ls=Date.now();g7(b)}hQa(a)},jQa=function(a){a.SP(1,0);
a.ix=o7(a,null,a.NA);t7(a)},gQa=function(a){a.Cm&&(a.Cm.abort(),a.Cm=null);
a.Ae&&(a.Ae.cancel(),a.Ae=null);a.ol&&(g.A.clearTimeout(a.ol),a.ol=null);u7(a);a.Og&&(a.Og.cancel(),a.Og=null);a.Jm&&(g.A.clearTimeout(a.Jm),a.Jm=null)},kQa=function(a,b){if(0==a.Oa)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new dQa(a.BR++,b));2!=a.Oa&&3!=a.Oa||t7(a)},lQa=function(a){var b=0;
a.Ae&&b++;a.Og&&b++;return b},t7=function(a){a.Og||a.Jm||(a.Jm=b7((0,g.C)(a.SK,a),0),a.vr=0)},nQa=function(a,b){if(1==a.Oa){if(!b){a.Xu=Math.floor(1E5*Math.random());
b=a.Xu++;var c=new e7(a,"",b,void 0);c.Co=a.Pj;var d=v7(a),e=a.ix.clone();g.kk(e,"RID",b);g.kk(e,"CVER","1");s7(a,e);TPa(c,e,d);a.Og=c;a.Oa=2}}else 3==a.Oa&&(b?mQa(a,b):0==a.i.length||a.Og||mQa(a))},mQa=function(a,b){if(b)if(6<a.Po){a.i=a.u.concat(a.i);
a.u.length=0;var c=a.Xu-1;b=v7(a)}else c=b.L,b=b.Up;else c=a.Xu++,b=v7(a);var d=a.ix.clone();g.kk(d,"SID",a.l);g.kk(d,"RID",c);g.kk(d,"AID",a.Nr);s7(a,d);c=new e7(a,a.l,c,a.vr+1);c.Co=a.Pj;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Og=c;TPa(c,d,b)},s7=function(a,b){a.Hf&&(a=a.Hf.sI())&&g.Db(a,function(c,d){g.kk(b,d,c)})},v7=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Po&&0<b){var d=a.i[0].i;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={yq:e.yq},f++){e.yq=a.i[f].i;var h=a.i[f].map;e.yq=6>=a.Po?f:e.yq-d;try{g.Db(h,function(l){return function(m,n){c.push("req"+l.yq+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.yq+"_type="+encodeURIComponent("_badmap"))}}a.u=a.u.concat(a.i.splice(0,b));
return c.join("&")},oQa=function(a){a.Ae||a.ol||(a.I=1,a.ol=b7((0,g.C)(a.RK,a),0),a.Tq=0)},w7=function(a){if(a.Ae||a.ol||3<=a.Tq)return!1;
a.I++;a.ol=b7((0,g.C)(a.RK,a),pQa(a,a.Tq));a.Tq++;return!0},p7=function(a,b,c){a.Uz=c;
a.Qj=b.Rk;a.C||jQa(a)},u7=function(a){null!=a.Xo&&(g.A.clearTimeout(a.Xo),a.Xo=null)},pQa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},x7=function(a,b){if(2==b||9==b){var c=null;
a.Hf&&(c=null);var d=(0,g.C)(a.QV,a);c||(c=new g.ck("//www.google.com/images/cleardot.gif"),B6(c));$Pa(c.toString(),1E4,d)}else d7(2);qQa(a,b)},qQa=function(a,b){a.Oa=0;
a.Hf&&a.Hf.IH(b);hQa(a);gQa(a)},hQa=function(a){a.Oa=0;
a.Qj=-1;if(a.Hf)if(0==a.u.length&&0==a.i.length)a.Hf.FB();else{g.qb(a.u);var b=g.qb(a.i);a.u.length=0;a.i.length=0;a.Hf.FB(b)}},o7=function(a,b,c){var d=g.lk(c);
if(""!=d.i)b&&g.ek(d,b+"."+d.i),g.fk(d,d.u);else{var e=window.location;d=qPa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Wt&&g.Db(a.Wt,function(f,h){g.kk(d,h,f)});
g.kk(d,"VER",a.Po);s7(a,d);return d},rQa=function(){},sQa=function(){this.i=[];
this.l=[]},tQa=function(a,b){this.action=a;
this.params=b||{}},y7=function(a,b){g.E.call(this);
this.i=new g.J(this.CU,0,this);g.F(this,this.i);this.Mf=5E3;this.l=0;if("function"===typeof a)b&&(a=(0,g.C)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.C)(a.handleEvent,a);else throw Error("Invalid listener argument");this.u=a},z7=function(a,b,c,d,e){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
e=void 0===e?!1:e;this.va=a;this.I=b;this.u=new g.cr;this.l=new y7(this.tV,this);this.i=null;this.ea=!1;this.C=null;this.V="";this.L=this.B=0;this.J=[];this.ya=c;this.Y=d;this.Aa=e},uQa=function(a){return{firstTestResults:[""],
secondTestResults:!a.i.Uz,sessionId:a.i.l,arrayId:a.i.Nr}},vQa=function(a,b){a.L=b||0;
a.l.stop();A7(a);a.i&&(3==a.i.getState()&&nQa(a.i),iQa(a.i));a.L=0},B7=function(a){return!!a.i&&3==a.i.getState()},A7=function(a){if(a.i){var b=a.Y(),c=a.i.Pj||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.i.Pj=c}},C7=function(a){this.port=this.domain="";
this.i="/api/lounge";this.l=!0;a=a||document.location.href;var b=Number(g.ii(4,a))||"";b&&(this.port=":"+b);this.domain=g.ji(a)||"";a=g.Wc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Fc(a,"10.0")&&(this.l=!1))},D7=function(a,b){var c=a.i;
a.l&&(c="https://"+a.domain+a.port+a.i);return g.ui(c+b,{})},E7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Pa(a.B,d,!0),onError:g.Pa(a.u,e),onTimeout:g.Pa(a.C,e)};c&&(a.postParams=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.at(b,a)},zQa=function(){var a=wQa;
xQa();F7.push(a);yQa()},G7=function(a,b){xQa();
var c=AQa(a,String(b));g.jb(F7)?BQa(c):(yQa(),g.Bb(F7,function(d){d(c)}))},xQa=function(){F7||(F7=g.Ha("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",F7,void 0))},BQa=function(a){var b=(H7+1)%50;
H7=b;I7[b]=a;J7||(J7=49==b)},yQa=function(){var a=F7;
if(I7[0]){var b=J7?H7:-1;do{b=(b+1)%50;var c=I7[b];g.Bb(a,function(d){d(c)})}while(b!=H7);
I7=Array(50);H7=-1;J7=!1}},AQa=function(a,b){var c=(Date.now()-CQa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},K7=function(a){g.P.call(this);
this.I=a;this.screens=[]},DQa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c)return a=c.name,c.id=b.id||c.id,c.name=b.name,c.token=b.token,c.uuid=b.uuid||c.uuid,c.name!=a;a.screens.push(b);return!0},EQa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.Ro(a.screens,function(f){return!!M6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=DQa(a,b[d])||c;return c},FQa=function(a,b){var c=a.screens.length;
a.screens=g.Ro(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},L7=function(a,b,c,d,e){g.P.call(this);
this.u=a;this.J=b;this.B=c;this.I=d;this.C=e;this.l=0;this.i=null;this.Ib=NaN},N7=function(a){K7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;M7(this);this.info("Initializing with "+K6(this.screens))},GQa=function(a){if(a.screens.length){var b=g.Re(a.screens,function(d){return d.id}),c=D7(a.l,"/pairing/get_lounge_token_batch");
E7(a.l,c,{screen_ids:b.join(",")},(0,g.C)(a.rQ,a),(0,g.C)(a.qQ,a))}},M7=function(a){if(g.Zr("deprecate_pair_servlet_enabled"))return EQa(a,[]);
var b=wPa(CPa());b=g.Ro(b,function(c){return!c.uuid});
return EQa(a,b)},O7=function(a,b){EPa(g.Re(a.screens,uPa));
b&&DPa()},Q7=function(a,b){g.P.call(this);
this.I=b;b=(b=g.gz("yt-remote-online-screen-ids")||"")?b.split(","):[];for(var c={},d=this.I(),e=0,f=d.length;e<f;++e){var h=d[e].id;c[h]=g.ib(b,h)}this.i=c;this.C=a;this.u=this.B=NaN;this.l=null;P7("Initialized with "+g.Lh(this.i))},R7=function(a,b,c){var d=D7(a.C,"/pairing/get_screen_availability");
E7(a.C,d,{lounge_token:b.token},(0,g.C)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.C)(function(){c(!1)},a))},S7=function(a,b){a:if(D6(b)!=D6(a.i))var c=!1;
else{c=g.Mb(b);for(var d=0,e=c.length;d<e;++d)if(!a.i[c[d]]){c=!1;break a}c=!0}c||(P7("Updated online screens: "+g.Lh(a.i)),a.i=b,a.X("screenChange"));HQa(a)},T7=function(a){isNaN(a.u)||g.Ws(a.u);
a.u=g.Us((0,g.C)(a.mE,a),0<a.B&&a.B<g.Ra()?2E4:1E4)},P7=function(a){G7("OnlineScreenService",a)},IQa=function(a){var b={};
g.Bb(a.I(),function(c){c.token?b[c.token]=c.id:this.Ud("Requesting availability of screen w/o lounge token.")});
return b},HQa=function(a){a=g.Mb(g.Eb(a.i,function(b){return b}));
g.yb(a);a.length?g.fz("yt-remote-online-screen-ids",a.join(","),60):g.iz("yt-remote-online-screen-ids")},U7=function(a,b){b=void 0===b?!1:b;
K7.call(this,"ScreenService");this.B=a;this.J=b;this.i=this.l=null;this.u=[];this.C={};JQa(this)},LQa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.C[b]);var h=a.yh(),l=c?N6(h,c):null;c&&(a.J||l)||(l=N6(h,b));if(l){l.uuid=b;var m=V7(a,l);R7(a.i,m,function(n){e(n?m:null)})}else c?KQa(a,c,(0,g.C)(function(n){var p=V7(this,new H6({name:d,
screenId:c,loungeToken:n,dialId:b||""}));R7(this.i,p,function(r){e(r?p:null)})},a),f):e(null)},MQa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},NQa=function(a,b,c){R7(a.i,b,c)},KQa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={postParams:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){f=h&&h.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.at(D7(a.B,"/pairing/get_lounge_token_batch"),e)},OQa=function(a){a.screens=a.l.yh();
var b=a.C,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+K6(a.screens))},JQa=function(a){W7(a);
a.l=new N7(a.B);a.l.subscribe("screenChange",(0,g.C)(a.AQ,a));OQa(a);a.J||(a.u=wPa(g.gz("yt-remote-automatic-screen-cache")||[]));W7(a);a.info("Initializing automatic screens: "+K6(a.u));a.i=new Q7(a.B,(0,g.C)(a.yh,a,!0));a.i.subscribe("screenChange",(0,g.C)(function(){this.X("onlineScreenChange")},a))},V7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=N6(a.u,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.u.push(b),a.J||PQa(a));W7(a);a.C[b.uuid]=b.id;g.fz("yt-remote-device-id-map",a.C,31536E3);return b},PQa=function(a){a=g.Ro(a.u,function(b){return"shortLived"!=b.idType});
g.fz("yt-remote-automatic-screen-cache",g.Re(a,uPa))},W7=function(a){a.C=g.gz("yt-remote-device-id-map")||{}},X7=function(a,b,c){g.P.call(this);
this.Aa=c;this.u=a;this.i=b;this.B=null},Y7=function(a,b){a.B=b;
a.X("sessionScreen",a.B)},QQa=function(a,b){a.B&&(a.B.token=b,V7(a.u,a.B));
a.X("sessionScreen",a.B)},Z7=function(a,b){G7(a.Aa,b)},$7=function(a,b,c){X7.call(this,a,b,"CastSession");
var d=this;this.config_=c;this.l=null;this.Y=(0,g.C)(this.EO,this);this.ya=(0,g.C)(this.VU,this);this.ea=g.Us(function(){RQa(d,null)},12E4);
this.J=this.C=this.I=this.L=0;this.va=!1;this.V="unknown"},a8=function(a,b){g.Ws(a.J);
a.J=0;0==b?SQa(a):a.J=g.Us(function(){SQa(a)},b)},SQa=function(a){TQa(a,"getLoungeToken");
g.Ws(a.C);a.C=g.Us(function(){UQa(a,null)},3E4)},TQa=function(a,b){a.info("sendYoutubeMessage_: "+b+" "+g.Lh(void 0));
var c={};c.type=b;a.l?a.l.sendMessage("urn:x-cast:com.google.youtube.mdx",c,g.Ia,(0,g.C)(function(){Z7(this,"Failed to send message: "+b+".")},a)):Z7(a,"Sending yt message without session: "+g.Lh(c))},b8=function(a,b){b?(a.info("onConnectedScreenId_: Received screenId: "+b),a.getScreen()&&a.getScreen().id==b||a.HI(b,function(c){Y7(a,c)},function(){return a.gg()},5)):a.gg(Error("Waiting for session status timed out."))},WQa=function(a,b,c){a.info("onConnectedScreenData_: Received screenData: "+JSON.stringify(b));
var d=new H6(b);VQa(a,d,function(e){e?(a.va=!0,V7(a.u,d),Y7(a,d),a.V="unknown",a8(a,c)):(g.ds(Error("CastSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online.")),a.gg())},5)},RQa=function(a,b){g.Ws(a.ea);
a.ea=0;b?a.config_.enableCastLoungeToken&&b.loungeToken?b.deviceId?a.getScreen()&&a.getScreen().uuid==b.deviceId||(b.loungeTokenRefreshIntervalMs?WQa(a,{name:a.i.friendlyName,screenId:b.screenId,loungeToken:b.loungeToken,dialId:b.deviceId,screenIdType:"shortLived"},b.loungeTokenRefreshIntervalMs):(g.ds(Error("No loungeTokenRefreshIntervalMs presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),b8(a,b.screenId))):(g.ds(Error("No device id presents in mdxSessionStatusData: "+JSON.stringify(b)+
".")),b8(a,b.screenId)):b8(a,b.screenId):a.gg(Error("Waiting for session status timed out."))},UQa=function(a,b){g.Ws(a.C);
a.C=0;var c=null;if(b)if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";else c="noLoungeTokenResponse";c?(a.info("Did not receive a new lounge token in onLoungeToken_ with data: "+(JSON.stringify(b)+", error: "+c)),a.V=c,a8(a,3E4)):(QQa(a,b.loungeToken),a.va=!1,a.V="unknown",a8(a,b.loungeTokenRefreshIntervalMs))},VQa=function(a,b,c,d){g.Ws(a.I);
a.I=0;NQa(a.u,b,function(e){e||0>d?c(e):a.I=g.Us(function(){VQa(a,b,c,d-1)},300)})},XQa=function(a){g.Ws(a.L);
a.L=0;g.Ws(a.I);a.I=0;g.Ws(a.ea);a.ea=0;g.Ws(a.C);a.C=0;g.Ws(a.J);a.J=0},c8=function(a,b,c,d){X7.call(this,a,b,"DialSession");
this.config_=d;this.l=this.L=null;this.ya="";this.Ga=c;this.Ja=null;this.ea=g.Ia;this.V=NaN;this.Da=(0,g.C)(this.FO,this);this.C=g.Ia;this.J=this.I=0;this.Y=!1;this.va="unknown"},d8=function(a){var b;
return!!(a.config_.enableDialLoungeToken&&(null==(b=a.l)?0:b.getDialAppInfo))},YQa=function(a){a.C=a.u.lG(a.ya,a.i.label,a.i.friendlyName,d8(a),function(b,c){a.C=g.Ia;
a.Y=!0;Y7(a,b);"shortLived"==b.idType&&0<c&&e8(a,c)},function(b){a.C=g.Ia;
a.gg(b)})},ZQa=function(a){var b={};
b.pairingCode=a.ya;b.theme=a.Ga;HPa()&&(b.env_useStageMdx=1);return g.si(b)},f8=function(a){return new Promise(function(b){a.ya=L6();
if(a.Ja){var c=new chrome.cast.DialLaunchResponse(!0,ZQa(a));b(c);YQa(a)}else a.ea=function(){g.Ws(a.V);a.ea=function(){};
a.V=NaN;var d=new chrome.cast.DialLaunchResponse(!0,ZQa(a));b(d);YQa(a)},a.V=g.Us(function(){a.ea()},100)})},aRa=function(a,b,c){a.info("initOnConnectedScreenDataPromise_: Received screenData: "+JSON.stringify(b));
var d=new H6(b);return(new Promise(function(e){$Qa(a,d,function(f){f?(a.Y=!0,V7(a.u,d),Y7(a,d),e8(a,c)):g.ds(Error("DialSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online."));e(f)},5)})).then(function(e){return e?new chrome.cast.DialLaunchResponse(!1):f8(a)})},bRa=function(a,b){var c=a.L.receiver.label,d=a.i.friendlyName;
return(new Promise(function(e){LQa(a.u,c,b,d,function(f){f&&f.token&&Y7(a,f);e(f)},function(f){Z7(a,"Failed to get DIAL screen: "+f);
e(null)})})).then(function(e){return e&&e.token?new chrome.cast.DialLaunchResponse(!1):f8(a)})},$Qa=function(a,b,c,d){g.Ws(a.I);
a.I=0;NQa(a.u,b,function(e){e||0>d?c(e):a.I=g.Us(function(){$Qa(a,b,c,d-1)},300)})},e8=function(a,b){a.info("getDialAppInfoWithTimeout_ "+b);
d8(a)&&(g.Ws(a.J),a.J=0,0==b?cRa(a):a.J=g.Us(function(){cRa(a)},b))},cRa=function(a){d8(a)&&a.l.getDialAppInfo(function(b){a.info("getDialAppInfo dialLaunchData: "+JSON.stringify(b));
b=b.extraData||{};var c=null;if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";c?(a.va=c,e8(a,3E4)):(a.Y=!1,a.va="unknown",QQa(a,b.loungeToken),e8(a,b.loungeTokenRefreshIntervalMs))},function(b){a.info("getDialAppInfo error: "+b);
a.va="noLoungeTokenResponse";e8(a,3E4)})},dRa=function(a){g.Ws(a.I);
a.I=0;g.Ws(a.J);a.J=0;a.C();a.C=function(){};
g.Ws(a.V)},g8=function(a,b){X7.call(this,a,b,"ManualSession");
this.l=g.Us((0,g.C)(this.Or,this,null),150)},h8=function(a,b){g.P.call(this);
this.config_=b;this.l=a;this.J=b.appId||"233637DE";this.B=b.theme||"cl";this.L=b.disableCastApi||!1;this.V=b.forceMirroring||!1;this.i=null;this.I=!1;this.u=[];this.C=(0,g.C)(this.NT,this)},eRa=function(a,b){return b?g.eb(a.u,function(c){return I6(b,c.label)},a):null},i8=function(a){G7("Controller",a)},wQa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},j8=function(a){return a.I||!!a.u.length||!!a.i},k8=function(a,b,c){b!=a.i&&(g.ff(a.i),(a.i=b)?(c?a.X("yt-remote-cast2-receiver-resumed",
b.i):a.X("yt-remote-cast2-receiver-selected",b.i),b.subscribe("sessionScreen",(0,g.C)(a.QK,a,b)),b.getScreen()?a.X("yt-remote-cast2-session-change",b.getScreen()):c&&a.i.Or(null)):a.X("yt-remote-cast2-session-change",null))},fRa=function(a){var b=a.l.kG(),c=a.i&&a.i.i;
a=g.Re(b,function(d){c&&I6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=eRa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},kRa=function(a,b,c,d){d.disableCastApi?l8("Cannot initialize because disabled by Mdx config."):gRa()?hRa(b,d)&&(m8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?iRa(a,c):(window.__onGCastApiAvailable=function(e,f){e?iRa(a,c):(n8("Failed to load cast API: "+f),o8(!1),m8(!1),g.iz("yt-remote-cast-available"),g.iz("yt-remote-cast-receiver"),
jRa(),c(!1))},d.loadCastApiSetupScript?g.kz("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?60<=U6()&&OPa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?W6():89<=U6()?QPa():(X6(),V6(PPa.map(LPa))))):l8("Cannot initialize because not running Chrome")},jRa=function(){l8("dispose");
var a=p8();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);lRa(!1);g.Ju(q8);q8.length=0},r8=function(){return!!g.gz("yt-remote-cast-installed")},mRa=function(){var a=g.gz("yt-remote-cast-receiver");
return a?a.friendlyName:null},nRa=function(){l8("clearCurrentReceiver");
g.iz("yt-remote-cast-receiver")},oRa=function(){return r8()?p8()?p8().getCastSession():(n8("getCastSelector: Cast is not initialized."),null):(n8("getCastSelector: Cast API is not installed!"),null)},t8=function(){r8()?p8()?s8()?(l8("Requesting cast selector."),p8().requestSession()):(l8("Wait for cast API to be ready to request the session."),q8.push(g.Iu("yt-remote-cast2-api-ready",t8))):n8("requestCastSelector: Cast is not initialized."):n8("requestCastSelector: Cast API is not installed!")},u8=
function(a,b){s8()?p8().setConnectedScreenStatus(a,b):n8("setConnectedScreenStatus called before ready.")},gRa=function(){var a=0<=g.Wc.search(/ (CrMo|Chrome|CriOS)\//);
return g.bj||a},pRa=function(a,b){p8().init(a,b)},hRa=function(a,b){var c=!1;
p8()||(a=new h8(a,b),a.subscribe("yt-remote-cast2-availability-change",function(d){g.fz("yt-remote-cast-available",d);F6("yt-remote-cast2-availability-change",d)}),a.subscribe("yt-remote-cast2-receiver-selected",function(d){l8("onReceiverSelected: "+d.friendlyName);
g.fz("yt-remote-cast-receiver",d);F6("yt-remote-cast2-receiver-selected",d)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(d){l8("onReceiverResumed: "+d.friendlyName);
g.fz("yt-remote-cast-receiver",d);F6("yt-remote-cast2-receiver-resumed",d)}),a.subscribe("yt-remote-cast2-session-change",function(d){l8("onSessionChange: "+J6(d));
d||g.iz("yt-remote-cast-receiver");F6("yt-remote-cast2-session-change",d)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),c=!0);
l8("cloudview.createSingleton_: "+c);return c},p8=function(){return g.Ha("yt.mdx.remote.cloudview.instance_")},iRa=function(a,b){o8(!0);
m8(!1);pRa(a,function(c){c?(lRa(!0),g.Ku("yt-remote-cast2-api-ready")):(n8("Failed to initialize cast API."),o8(!1),g.iz("yt-remote-cast-available"),g.iz("yt-remote-cast-receiver"),jRa());b(c)})},l8=function(a){G7("cloudview",a)},n8=function(a){G7("cloudview",a)},o8=function(a){l8("setCastInstalled_ "+a);
g.fz("yt-remote-cast-installed",a)},s8=function(){return!!g.Ha("yt.mdx.remote.cloudview.apiReady_")},lRa=function(a){l8("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},m8=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},v8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.I=this.J=0;this.trackData=null;this.hasNext=this.jk=!1;this.L=this.C=this.i=this.B=0;this.u=NaN;this.l=!1;this.reset(a)},w8=function(a){a.audioTrackId=null;
a.trackData=null;a.playerState=-1;a.jk=!1;a.hasNext=!1;a.J=0;a.I=g.Ra();a.B=0;a.i=0;a.C=0;a.L=0;a.u=NaN;a.l=!1},x8=function(a){return a.zc()?(g.Ra()-a.I)/1E3:0},y8=function(a,b){a.J=b;
a.I=g.Ra()},z8=function(a){switch(a.playerState){case 1:case 1081:return(g.Ra()-a.I)/1E3+a.J;
case -1E3:return 0}return a.J},A8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&w8(a)},B8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Wb(a.trackData);b.hasPrevious=a.jk;b.hasNext=a.hasNext;b.playerTime=a.J;b.playerTimeAt=a.I;b.seekableStart=a.B;b.seekableEnd=a.i;b.duration=a.C;b.loadedTime=a.L;b.liveIngestionTime=a.u;return b},D8=function(a,b){g.P.call(this);
this.Oa=0;this.u=a;this.C=[];this.B=new sQa;this.l=this.i=null;this.L=(0,g.C)(this.lS,this);this.I=(0,g.C)(this.fv,this);this.J=(0,g.C)(this.kS,this);this.V=(0,g.C)(this.sS,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.BE,this),qRa(this))):c=3;0!=c&&(b?this.BE(c):g.Us((0,g.C)(function(){this.BE(c)},this),0));
(a=oRa())&&C8(this,a);this.subscribe("yt-remote-cast2-session-change",this.V)},E8=function(a){return new v8(a.u.getPlayerContextData())},qRa=function(a){g.Bb("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange multiStateLoopEnabled".split(" "),function(b){this.C.push(this.u.subscribe(b,g.Pa(this.JT,b),this))},a)},rRa=function(a){g.Bb(a.C,function(b){this.u.unsubscribeByKey(b)},a);
a.C.length=0},F8=function(a){return 1==a.getState()},G8=function(a,b){var c=a.B;
50>c.i.length+c.l.length&&a.B.l.push(b)},I8=function(a,b,c){var d=E8(a);
y8(d,c);-1E3!=d.playerState&&(d.playerState=b);H8(a,d)},J8=function(a,b,c){a.u.sendMessage(b,c)},H8=function(a,b){rRa(a);
a.u.setPlayerContextData(B8(b));qRa(a)},C8=function(a,b){a.l&&(a.l.removeUpdateListener(a.L),a.l.removeMediaListener(a.I),a.fv(null));
a.l=b;a.l&&(G7("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.L),a.l.addMediaListener(a.I),a.l.media.length&&a.fv(a.l.media[0]))},sRa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=E8(a);b.contentId!=d.videoId&&G7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;y8(d,a.i.getEstimatedTime());H8(a,d)}else G7("CP","No cast media video. Ignoring state update.")},K8=function(a,b,c){return(0,g.C)(function(d){this.Ud("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Ud("Retrying "+b+" using MDx browser channel."),J8(this,b,c))},a)},L8=function(a,b,c){g.P.call(this);
this.C=NaN;this.va=!1;this.L=this.J=this.ea=this.Y=NaN;this.V=[];this.B=this.I=this.u=this.kc=this.i=null;this.Aa=a;this.V.push(g.$t(window,"beforeunload",(0,g.C)(this.mQ,this)));this.l=[];this.kc=new v8;this.Da=b.id;this.ya=b.idType;this.i=tRa(this,c);this.i.subscribe("handlerOpened",this.pS,this);this.i.subscribe("handlerClosed",this.mS,this);this.i.subscribe("handlerError",this.nS,this);this.i.subscribe("handlerMessage",this.oS,this);this.i.xz(b.token);this.subscribe("remoteQueueChange",function(){var d=
this.kc.videoId;g.jz()&&g.fz("yt-remote-session-video-id",d)},this)},M8=function(a){G7("conn",a)},tRa=function(a,b){return new z7(D7(a.Aa,"/bc"),b,!1,function(){return a.pG()},"shortLived"==a.ya)},N8=function(a,b){a.X("proxyStateChange",b)},uRa=function(a){a.C=g.Us((0,g.C)(function(){M8("Connecting timeout");
this.jr(1)},a),2E4)},O8=function(a){g.Ws(a.C);
a.C=NaN},P8=function(a){g.Ws(a.Y);
a.Y=NaN},vRa=function(a){Q8(a);
a.ea=g.Us((0,g.C)(function(){R8(this,"getNowPlaying")},a),2E4)},Q8=function(a){g.Ws(a.ea);
a.ea=NaN},xRa=function(a,b){b&&(O8(a),P8(a));
var c=B7(a.i)&&isNaN(a.C);b==c?b&&(N8(a,1),R8(a,"getSubtitlesTrack")):b?(a.GI()&&a.kc.reset(),N8(a,1),R8(a,"getNowPlaying"),wRa(a)):a.jr(1)},yRa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.kc.videoId&&(g.Rb(b.params)?a.kc.trackData=null:a.kc.trackData=b.params,a.X("remotePlayerChange"))},zRa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.kc.listId=b.params.listId||a.kc.listId;A8(a.kc,c,d);a.X("remoteQueueChange")},BRa=function(a,b){b.params=b.params||{};
zRa(a,b);ARa(a,b);a.X("autoplayDismissed")},ARa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
y8(a.kc,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.kc.playerState&&(c=-1E3);a.kc.playerState=c;c=Number(b.params.loadedTime);a.kc.L=isNaN(c)?0:c;a.kc.vj(Number(b.params.duration));c=a.kc;var d=Number(b.params.liveIngestionTime);c.u=d;c.l=isNaN(d)?!1:!0;c=a.kc;d=Number(b.params.seekableStartTime);b=Number(b.params.seekableEndTime);c.B=isNaN(d)?0:d;c.i=isNaN(b)?0:b;1==a.kc.playerState?vRa(a):Q8(a);a.X("remotePlayerChange")},CRa=function(a,b){if(-1E3!=a.kc.playerState){var c=
1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.kc.playerState=c;b=parseInt(b.params.currentTime,10);y8(a.kc,isNaN(b)?0:b);a.X("remotePlayerChange")}},DRa=function(a,b){var c="true"==b.params.muted;
a.kc.volume=parseInt(b.params.volume,10);a.kc.muted=c;a.X("remotePlayerChange")},ERa=function(a,b){a.I=b.params.videoId;
a.X("nowAutoplaying",parseInt(b.params.timeout,10))},FRa=function(a,b){var c="true"==b.params.hasNext;
a.kc.jk="true"==b.params.hasPrevious;a.kc.hasNext=c;a.X("previousNextChange")},wRa=function(a){g.Ws(a.L);
a.L=g.Us((0,g.C)(a.jr,a,1),864E5)},R8=function(a,b,c){c?M8("Sending: action="+b+", params="+g.Lh(c)):M8("Sending: action="+b);
a.i.sendMessage(b,c)},S8=function(a){K7.call(this,"ScreenServiceProxy");
this.Ie=a;this.i=[];this.i.push(this.Ie.$_s("screenChange",(0,g.C)(this.JO,this)));this.i.push(this.Ie.$_s("onlineScreenChange",(0,g.C)(this.rT,this)))},JRa=function(a,b){GPa();
if(!T6||!T6.get("yt-remote-disable-remote-module-for-dev")){b=g.N("MDX_CONFIG")||b;yPa();R6();T8||(T8=new C7(b?b.loungeApiHost:void 0),HPa()&&(T8.i="/api/loungedev"));U8||(U8=g.Ha("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",U8,void 0));GRa();var c=V8();if(!c){var d=new U7(T8,b?b.disableAutomaticScreenCache||!1:!1);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=V8();var e={};b&&(e={appId:b.appId,disableDial:b.disableDial,theme:b.theme,loadCastApiSetupScript:b.loadCastApiSetupScript,
disableCastApi:b.disableCastApi,enableDialLoungeToken:b.enableDialLoungeToken,enableCastLoungeToken:b.enableCastLoungeToken,forceMirroring:b.forceMirroring});kRa(a,d,function(f){f?W8()&&u8(W8(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){F6("yt-remote-receiver-availability-change")})},e)}b&&!g.Ha("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),X8("Initializing: "+g.Lh(b)),Y8.push(g.Iu("yt-remote-cast2-availability-change",function(){F6("yt-remote-receiver-availability-change")})),
Y8.push(g.Iu("yt-remote-cast2-receiver-selected",function(){Z8(null);
F6("yt-remote-auto-connect","cast-selector-receiver")})),Y8.push(g.Iu("yt-remote-cast2-receiver-resumed",function(){F6("yt-remote-receiver-resumed","cast-selector-receiver")})),Y8.push(g.Iu("yt-remote-cast2-session-change",HRa)),Y8.push(g.Iu("yt-remote-connection-change",function(f){f?u8(W8(),"YouTube TV"):$8()||(u8(null,null),nRa())})),a=a9(),b.isAuto&&(a.id+="#dial"),e=b.capabilities||[],g.Zr("desktop_enable_autoplay")&&e.push("atp"),0<e.length&&(a.capabilities=e),a.name=b.device,a.app=b.app,(b=
b.theme)&&(a.theme=b),X8(" -- with channel params: "+g.Lh(a)),a?(g.fz("yt-remote-session-app",a.app),g.fz("yt-remote-session-name",a.name)):(g.iz("yt-remote-session-app"),g.iz("yt-remote-session-name")),g.Ga("yt.mdx.remote.channelParams_",a,void 0),c.start(),W8()||IRa())}},KRa=function(){var a=V8().Ie.$_gos();
var b=b9();b&&c9()&&(M6(a,b)||a.push(b));return xPa(a)},d9=function(){var a=LRa();
!a&&r8()&&mRa()&&(a={key:"cast-selector-receiver",name:mRa()});return a},LRa=function(){var a=KRa(),b=b9();
b||(b=$8());return g.eb(a,function(c){return b&&I6(b,c.key)?!0:!1})},b9=function(){var a=W8();
if(!a)return null;var b=V8().yh();return N6(b,a)},HRa=function(a){X8("remote.onCastSessionChange_: "+J6(a));
if(a){var b=b9();if(b&&b.id==a.id){if(u8(b.id,"YouTube TV"),"shortLived"==a.idType&&(a=a.token))e9&&(e9.token=a),(b=c9())&&b.xz(a)}else b&&f9(),g9(a,1)}else c9()&&f9()},f9=function(){s8()?p8().stopSession():n8("stopSession called before API ready.");
var a=c9();a&&(a.disconnect(1),h9(null))},i9=function(){var a=c9();
return!!a&&3!=a.getProxyState()},X8=function(a){G7("remote",a)},V8=function(){if(!j9){var a=g.Ha("yt.mdx.remote.screenService_");
j9=a?new S8(a):null}return j9},W8=function(){return g.Ha("yt.mdx.remote.currentScreenId_")},MRa=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},NRa=function(){return g.Ha("yt.mdx.remote.connectData_")},Z8=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},c9=function(){return g.Ha("yt.mdx.remote.connection_")},h9=function(a){var b=c9();
Z8(null);a||MRa("");g.Ga("yt.mdx.remote.connection_",a,void 0);U8&&(g.Bb(U8,function(c){c(a)}),U8.length=0);
b&&!a?F6("yt-remote-connection-change",!1):!b&&a&&F6("yt-remote-connection-change",!0)},$8=function(){var a=g.jz();
if(!a)return null;var b=V8();if(!b)return null;b=b.yh();return N6(b,a)},g9=function(a,b){W8();
b9()&&b9();k9?e9=a:(MRa(a.id),a=new L8(T8,a,a9()),a.connect(b,NRa()),a.subscribe("beforeDisconnect",function(c){F6("yt-remote-before-disconnect",c)}),a.subscribe("beforeDispose",function(){c9()&&(c9(),h9(null))}),a.subscribe("browserChannelAuthError",function(){var c=b9();
c&&"shortLived"==c.idType&&(s8()?p8().handleBrowserChannelAuthError():n8("refreshLoungeToken called before API ready."))}),h9(a))},IRa=function(){var a=$8();
a?(X8("Resume connection to: "+J6(a)),g9(a,0)):(S6(),nRa(),X8("Skipping connecting because no session screen found."))},GRa=function(){var a=a9();
if(g.Rb(a)){a=Q6();var b=g.gz("yt-remote-session-name")||"",c=g.gz("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},a9=function(){return g.Ha("yt.mdx.remote.channelParams_")||{}},l9=function(a,b,c){g.E.call(this);
var d=this;this.l=a;this.G=b;this.Qb=c;this.events=new g.vN(this);this.ea=this.events.N(this.G,"onVolumeChange",function(e){ORa(d,e)});
this.C=!1;this.suggestion=null;this.I=new g.FK(64);this.i=new g.J(this.PL,500,this);this.u=new g.J(this.QL,1E3,this);this.L=new Y6(this.iW,0,this);this.B={};this.V=new g.J(this.xM,1E3,this);this.J=new Z6(this.seekTo,1E3,this);this.Y=g.Ia;g.F(this,this.events);this.events.N(b,"onCaptionsTrackListChanged",this.aT);this.events.N(b,"captionschanged",this.iS);this.events.N(b,"captionssettingschanged",this.WL);this.events.N(b,"videoplayerreset",this.Sy);this.events.N(b,"mdxautoplaycancel",function(){d.Qb.bI()});
a=this.Qb;a.isDisposed();a.subscribe("proxyStateChange",this.MK,this);a.subscribe("remotePlayerChange",this.wv,this);a.subscribe("remoteQueueChange",this.Sy,this);a.subscribe("previousNextChange",this.JK,this);a.subscribe("nowAutoplaying",this.DK,this);a.subscribe("autoplayDismissed",this.gK,this);g.F(this,this.i);g.F(this,this.u);g.F(this,this.L);g.F(this,this.V);g.F(this,this.J);this.WL();this.Sy();this.wv()},ORa=function(a,b){if(m9(a)){a.Qb.unsubscribe("remotePlayerChange",a.wv,a);
var c=Math.round(b.volume);b=!!b.muted;var d=E8(a.Qb);if(c!==d.volume||b!==d.muted)a.Qb.setVolume(c,b),a.V.start();a.Qb.subscribe("remotePlayerChange",a.wv,a)}},PRa=function(a){a.Sb(0);
a.i.stop();a.Lb(new g.FK(64))},n9=function(a,b){if(m9(a)&&!a.C){var c=null;
b&&(c={style:a.G.getSubtitlesUserSettings()},g.Yb(c,b));a.Qb.oG(a.G.getVideoData(1).videoId,c);a.B=E8(a.Qb).trackData}},o9=function(a,b){var c=a.G.getPlaylist();
if(null===c||void 0===c?0:c.listId){var d=c.index;var e=c.listId.toString()}c=a.G.getVideoData(1);a.Qb.playVideo(c.videoId,b,d,e,c.playerParams,c.La,nPa(c));a.Lb(new g.FK(1))},QRa=function(a,b){if(b){var c=a.G.getOption("captions","tracklist",{bJ:1});
c&&c.length?(a.G.setOption("captions","track",b),a.C=!1):(a.G.loadModule("captions"),a.C=!0)}else a.G.setOption("captions","track",{})},m9=function(a){return E8(a.Qb).videoId===a.G.getVideoData(1).videoId},p9=function(){g.V.call(this,{D:"div",
K:"ytp-mdx-manual-pairing-popup-dialog",U:{role:"dialog"},S:[{D:"div",K:"ytp-mdx-manual-pairing-popup-dialog-inner-content",S:[{D:"div",K:"ytp-mdx-manual-pairing-popup-title",ra:"Pronto dejar\u00e1 de ser posible establecer una conexi\u00f3n web con una TV mediante un c\u00f3digo"},{D:"div",K:"ytp-mdx-manual-pairing-popup-buttons",S:[{D:"button",Ea:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],ra:"M\u00e1s informaci\u00f3n"},{D:"button",Ea:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],
ra:"Aceptar"}]}]}]});this.i=new g.jM(this,250);this.learnMoreButton=this.Ca("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.Ca("ytp-mdx-manual-pairing-popup-ok");g.F(this,this.i);this.N(this.learnMoreButton,"click",this.l);this.N(this.okButton,"click",this.u)},q9=function(){g.V.call(this,{D:"div",
K:"ytp-mdx-popup-dialog",U:{role:"dialog"},S:[{D:"div",K:"ytp-mdx-popup-dialog-inner-content",S:[{D:"div",K:"ytp-mdx-popup-title",ra:"No has iniciado sesi\u00f3n"},{D:"div",K:"ytp-mdx-popup-description",ra:"Los v\u00eddeos que veas podr\u00edan aparecer en el historial de reproducciones de la TV e influir en las recomendaciones. Puedes evitarlo si cancelas e inicias sesi\u00f3n en YouTube desde tu ordenador."},{D:"div",K:"ytp-mdx-privacy-popup-buttons",S:[{D:"button",Ea:["ytp-button","ytp-mdx-privacy-popup-cancel"],
ra:"Cancelar"},{D:"button",Ea:["ytp-button","ytp-mdx-privacy-popup-confirm"],ra:"Confirmar"}]}]}]});this.i=new g.jM(this,250);this.cancelButton=this.Ca("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.Ca("ytp-mdx-privacy-popup-confirm");g.F(this,this.i);this.N(this.cancelButton,"click",this.l);this.N(this.confirmButton,"click",this.u)},r9=function(a){g.V.call(this,{D:"div",
K:"ytp-remote",S:[{D:"div",K:"ytp-remote-display-status",S:[{D:"div",K:"ytp-remote-display-status-icon",S:[g.Wqa()]},{D:"div",K:"ytp-remote-display-status-text",ra:"{{statustext}}"}]}]});this.api=a;this.i=new g.jM(this,250);g.F(this,this.i);this.N(a,"presentingplayerstatechange",this.l);RRa(this,a.ub())},RRa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
b=g.U(b,128)?g.hJ("No se ha podido reproducir el v\u00eddeo en $RECEIVER_NAME",c):b.zc()||g.U(b,4)?g.hJ("El v\u00eddeo se est\u00e1 reproduciendo en $RECEIVER_NAME",c):g.hJ("Conectado a $RECEIVER_NAME",c);a.Sa("statustext",b);a.i.show()}else a.i.hide()},s9=function(a,b){g.uQ.call(this,"Reproducir en",0,a,b);
this.G=a;this.Jn={};this.N(a,"onMdxReceiversChange",this.C);this.N(a,"presentingplayerstatechange",this.C);this.C()},t9=function(a){g.EN.call(this,a);
this.ij={key:L6(),name:"Este ordenador"};this.Sh=null;this.subscriptions=[];this.ZD=this.Qb=null;this.Jn=[this.ij];this.Em=this.ij;this.ld=new g.FK(64);this.AJ=0;this.jf=-1;this.Sr=null;this.Cv=this.py=!1;this.Ul=this.ds=null;if(!g.XF(this.player.T())&&!g.YF(this.player.T())){a=this.player;var b=g.iN(a);b&&(b=b.Sm())&&(b=new s9(a,b),g.F(this,b));b=new r9(a);g.F(this,b);g.sN(a,b.element,4);this.ds=new q9;g.F(this,this.ds);g.sN(a,this.ds.element,4);g.S(this.player.T().experiments,"pair_servlet_deprecation_warning_enabled")&&
!g.S(this.player.T().experiments,"deprecate_pair_servlet_enabled")&&(this.Sr=new p9,g.F(this,this.Sr),g.sN(a,this.Sr.element,4));this.Cv=!!$8();this.py=!!g.gz("yt-remote-manual-pairing-warning-shown")}},u9=function(a){a.Ul&&(a.player.removeEventListener("presentingplayerstatechange",a.Ul),a.Ul=null)},SRa=function(a,b,c){a.ld=c;
a.player.X("presentingplayerstatechange",new g.VI(c,b))},TRa=function(a,b,c){var d=!1;
1===b?d=!a.Cv:2===b&&(d=!a.py);d&&g.XI(c,8)&&(a.player.pauseVideo(),u9(a))},v9=function(a,b){if(b.key!==a.Em.key)if(b.key===a.ij.key)f9();
else{if(a.Sr&&!a.py&&b!==a.ij&&"cast-selector-receiver"!==b.key&&g.EG(a.player.T()))URa(a);else{var c;(c=!g.S(a.player.T().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.N("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.N("SESSION_INDEX")&&!g.N("LOGGED_IN")))||a.Cv||!a.ds);(c?0:g.EG(a.player.T())||g.IG(a.player.T()))&&VRa(a)}a.Em=b;if(!a.player.T().Z("disable_mdx_connection_in_mdx_module_for_music_web")||!g.YF(a.player.T())){var d=a.player.getPlaylistId();c=a.player.getVideoData(1);
var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&g.S(a.player.T().experiments,"should_clear_video_data_on_player_cued_unstarted"))a=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.length;l++)h[l]=f.ib(l).videoId}else h=[e];f=a.player.getCurrentTime(1);a={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.La,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=nPa(c))&&(a.locationInfo=c)}X8("Connecting to: "+
g.Lh(b));"cast-selector-receiver"==b.key?(Z8(a||null),b=a||null,s8()?p8().setLaunchParams(b):n8("setLaunchParams called before ready.")):!a&&i9()&&W8()==b.key?F6("yt-remote-connection-change",!0):(f9(),Z8(a||null),a=V8().yh(),(b=N6(a,b.key))&&g9(b,1))}}},VRa=function(a){a.player.ub().zc()?a.player.pauseVideo():(a.Ul=function(b){TRa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.Ul));
a.ds&&a.ds.Yc();c9()||(k9=!0)},URa=function(a){a.player.ub().zc()?a.player.pauseVideo():(a.Ul=function(b){TRa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.Ul));
a.Sr&&a.Sr.Yc();c9()||(k9=!0)},XPa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},l7={"'":"\\'"},tPa={hX:"atp",S6:"ska",I5:"que",U3:"mus",R6:"sus",d0:"dsp",c6:"seq",x3:"mic",c_:"dpa",vX:"cds",S3:"mlm"},T6,P6="",NPa=IPa("loadCastFramework")||IPa("loadCastApplicationFramework"),PPa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Sa(Y6,g.E);g.k=Y6.prototype;g.k.xO=function(a){this.B=arguments;this.i=!1;this.Ib?this.u=g.Ra()+this.Mf:this.Ib=g.lh(this.C,this.Mf)};
g.k.stop=function(){this.Ib&&(g.A.clearTimeout(this.Ib),this.Ib=null);this.u=null;this.i=!1;this.B=[]};
g.k.pause=function(){++this.l};
g.k.resume=function(){this.l&&(--this.l,!this.l&&this.i&&(this.i=!1,this.I.apply(null,this.B)))};
g.k.xa=function(){this.stop();Y6.Td.xa.call(this)};
g.k.yO=function(){this.Ib&&(g.A.clearTimeout(this.Ib),this.Ib=null);this.u?(this.Ib=g.lh(this.C,this.u-g.Ra()),this.u=null):this.l?this.i=!0:(this.i=!1,this.I.apply(null,this.B))};g.v(Z6,g.E);g.k=Z6.prototype;g.k.jG=function(a){this.u=arguments;this.Ib||this.l?this.i=!0:$6(this)};
g.k.stop=function(){this.Ib&&(g.A.clearTimeout(this.Ib),this.Ib=null,this.i=!1,this.u=null)};
g.k.pause=function(){this.l++};
g.k.resume=function(){this.l--;this.l||!this.i||this.Ib||(this.i=!1,$6(this))};
g.k.xa=function(){g.E.prototype.xa.call(this);this.stop()};a7.prototype.stringify=function(a){return g.A.JSON.stringify(a,void 0)};
a7.prototype.parse=function(a){return g.A.JSON.parse(a,void 0)};var c7=new g.Jf;g.v(RPa,g.lf);g.k=e7.prototype;g.k.Co=null;g.k.xj=!1;g.k.Ks=null;g.k.qF=null;g.k.ls=null;g.k.Ds=null;g.k.xm=null;g.k.Mn=null;g.k.Up=null;g.k.We=null;g.k.pw=0;g.k.Bj=null;g.k.Wz=null;g.k.pm=null;g.k.ot=-1;g.k.EL=!0;g.k.Oo=!1;g.k.KA=0;g.k.jz=null;var VPa={},h7={};g.k=e7.prototype;g.k.setTimeout=function(a){this.C=a};
g.k.zO=function(a){a=a.target;var b=this.jz;b&&3==g.Hi(a)?b.jG():this.DM(a)};
g.k.DM=function(a){try{if(a==this.We)a:{var b=g.Hi(this.We),c=this.We.l,d=this.We.getStatus();if(g.fe&&!g.$d(10)||g.kg&&!g.Zd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Vk&&!g.Mi(this.We))break a;this.Oo||4!=b||7==c||(8==c||0>=d?this.i.lj(3):this.i.lj(2));m7(this);var e=this.We.getStatus();this.ot=e;var f=g.Mi(this.We);(this.xj=200==e)?(4==b&&j7(this),this.I?(WPa(this,b,f),g.Vk&&this.xj&&3==b&&(this.B.Pa(this.u,"tick",this.bV),this.u.start())):i7(this,f),this.xj&&!this.Oo&&(4==b?this.i.Fw(this):
(this.xj=!1,g7(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.pm=3,d7(13)):(this.pm=0,d7(14)),j7(this),k7(this))}}catch(h){this.We&&g.Mi(this.We)}finally{}};
g.k.bV=function(){var a=g.Hi(this.We),b=g.Mi(this.We);this.pw<b.length&&(m7(this),WPa(this,a,b),this.xj&&4!=a&&g7(this))};
g.k.KU=function(a){b7((0,g.C)(this.JU,this,a),0)};
g.k.JU=function(a){this.Oo||(m7(this),i7(this,a),g7(this))};
g.k.UK=function(a){b7((0,g.C)(this.IU,this,a),0)};
g.k.IU=function(a){this.Oo||(j7(this),this.xj=a,this.i.Fw(this),this.i.lj(4))};
g.k.cancel=function(){this.Oo=!0;j7(this)};
g.k.SU=function(){this.Ks=null;var a=Date.now();0<=a-this.qF?(2!=this.Ds&&this.i.lj(3),j7(this),this.pm=2,d7(18),k7(this)):ZPa(this,this.qF-a)};
g.k.getLastError=function(){return this.pm};g.k=bQa.prototype;g.k.LA=null;g.k.eh=null;g.k.kz=!1;g.k.RL=null;g.k.hx=null;g.k.hD=null;g.k.MA=null;g.k.Oa=null;g.k.Rk=-1;g.k.qt=null;g.k.Ft=null;g.k.connect=function(a){this.MA=a;a=o7(this.i,null,this.MA);d7(3);this.RL=Date.now();var b=this.i.J;null!=b?(this.qt=b[0],(this.Ft=b[1])?(this.Oa=1,cQa(this)):(this.Oa=2,q7(this))):(C6(a,"MODE","init"),this.eh=new e7(this,void 0,void 0,void 0),this.eh.Co=this.LA,f7(this.eh,a,!1,null,!0),this.Oa=0)};
g.k.sP=function(a){if(a)this.Oa=2,q7(this);else{d7(4);var b=this.i;b.Qj=b.Cm.Rk;x7(b,9)}a&&this.lj(2)};
g.k.SB=function(a){return this.i.SB(a)};
g.k.abort=function(){this.eh&&(this.eh.cancel(),this.eh=null);this.Rk=-1};
g.k.df=function(){return!1};
g.k.NK=function(a,b){this.Rk=a.ot;if(0==this.Oa)if(b){try{var c=this.l.parse(b)}catch(d){a=this.i;a.Qj=this.Rk;x7(a,2);return}this.qt=c[0];this.Ft=c[1]}else a=this.i,a.Qj=this.Rk,x7(a,2);else if(2==this.Oa)if(this.kz)d7(7),this.hD=Date.now();else if("11111"==b){if(d7(6),this.kz=!0,this.hx=Date.now(),a=this.hx-this.RL,!g.fe||g.$d(10)||500>a)this.Rk=200,this.eh.cancel(),d7(12),p7(this.i,this,!0)}else d7(8),this.hx=this.hD=Date.now(),this.kz=!1};
g.k.Fw=function(){this.Rk=this.eh.ot;if(this.eh.xj)0==this.Oa?this.Ft?(this.Oa=1,cQa(this)):(this.Oa=2,q7(this)):2==this.Oa&&((!g.fe||g.$d(10)?!this.kz:200>this.hD-this.hx)?(d7(11),p7(this.i,this,!1)):(d7(12),p7(this.i,this,!0)));else{0==this.Oa?d7(9):2==this.Oa&&d7(10);var a=this.i;this.eh.getLastError();a.Qj=this.Rk;x7(a,2)}};
g.k.Tv=function(){return this.i.Tv()};
g.k.isActive=function(){return this.i.isActive()};
g.k.lj=function(a){this.i.lj(a)};g.k=r7.prototype;g.k.Pj=null;g.k.Wt=null;g.k.Og=null;g.k.Ae=null;g.k.NA=null;g.k.ix=null;g.k.tH=null;g.k.Gw=null;g.k.Xu=0;g.k.BR=0;g.k.Hf=null;g.k.Jm=null;g.k.ol=null;g.k.Xo=null;g.k.Cm=null;g.k.Uz=null;g.k.Nr=-1;g.k.zJ=-1;g.k.Qj=-1;g.k.vr=0;g.k.Tq=0;g.k.Po=8;g.Sa(eQa,g.lf);g.Sa(fQa,g.lf);g.k=r7.prototype;g.k.connect=function(a,b,c,d,e){d7(0);this.NA=b;this.Wt=c||{};d&&void 0!==e&&(this.Wt.OSID=d,this.Wt.OAID=e);this.C?(b7((0,g.C)(this.OH,this,a),100),jQa(this)):this.OH(a)};
g.k.OH=function(a){this.Cm=new bQa(this);this.Cm.LA=this.Pj;this.Cm.l=this.B;this.Cm.connect(a)};
g.k.df=function(){return 0==this.Oa};
g.k.getState=function(){return this.Oa};
g.k.SK=function(a){this.Jm=null;nQa(this,a)};
g.k.RK=function(){this.ol=null;this.Ae=new e7(this,this.l,"rpc",this.I);this.Ae.Co=this.Pj;this.Ae.KA=0;var a=this.tH.clone();g.kk(a,"RID","rpc");g.kk(a,"SID",this.l);g.kk(a,"CI",this.Uz?"0":"1");g.kk(a,"AID",this.Nr);s7(this,a);if(!g.fe||g.$d(10))g.kk(a,"TYPE","xmlhttp"),f7(this.Ae,a,!0,this.Gw,!1);else{g.kk(a,"TYPE","html");var b=this.Ae,c=!!this.Gw;b.Ds=3;b.xm=B6(a.clone());YPa(b,c)}};
g.k.NK=function(a,b){if(0!=this.Oa&&(this.Ae==a||this.Og==a))if(this.Qj=a.ot,this.Og==a&&3==this.Oa)if(7<this.Po){try{var c=this.B.parse(b)}catch(d){c=null}if(Array.isArray(c)&&3==c.length)if(a=c,0==a[0])a:{if(!this.ol){if(this.Ae)if(this.Ae.ls+3E3<this.Og.ls)u7(this),this.Ae.cancel(),this.Ae=null;else break a;w7(this);d7(19)}}else this.zJ=a[1],0<this.zJ-this.Nr&&37500>a[2]&&this.Uz&&0==this.Tq&&!this.Xo&&(this.Xo=b7((0,g.C)(this.fS,this),6E3));else x7(this,11)}else null!=b&&x7(this,11);else if(this.Ae==
a&&u7(this),!g.uc(b))for(a=this.B.parse(b),b=0;b<a.length;b++)c=a[b],this.Nr=c[0],c=c[1],2==this.Oa?"c"==c[0]?(this.l=c[1],this.Gw=c[2],c=c[3],null!=c?this.Po=c:this.Po=6,this.Oa=3,this.Hf&&this.Hf.KH(),this.tH=o7(this,this.Tv()?this.Gw:null,this.NA),oQa(this)):"stop"==c[0]&&x7(this,7):3==this.Oa&&("stop"==c[0]?x7(this,7):"noop"!=c[0]&&this.Hf&&this.Hf.JH(c),this.Tq=0)};
g.k.fS=function(){null!=this.Xo&&(this.Xo=null,this.Ae.cancel(),this.Ae=null,w7(this),d7(20))};
g.k.Fw=function(a){if(this.Ae==a){u7(this);this.Ae=null;var b=2}else if(this.Og==a)this.Og=null,b=1;else return;this.Qj=a.ot;if(0!=this.Oa)if(a.xj)if(1==b){b=Date.now()-a.ls;var c=c7;c.dispatchEvent(new eQa(c,a.Up?a.Up.length:0,b,this.vr));t7(this);this.u.length=0}else oQa(this);else{c=a.getLastError();var d;if(!(d=3==c||7==c||0==c&&0<this.Qj)){if(d=1==b)this.Og||this.Jm||1==this.Oa||2<=this.vr?d=!1:(this.Jm=b7((0,g.C)(this.SK,this,a),pQa(this,this.vr)),this.vr++,d=!0);d=!(d||2==b&&w7(this))}if(d)switch(c){case 1:x7(this,
5);break;case 4:x7(this,10);break;case 3:x7(this,6);break;case 7:x7(this,12);break;default:x7(this,2)}}};
g.k.SP=function(a){if(!g.ib(arguments,this.Oa))throw Error("Unexpected channel state: "+this.Oa);};
g.k.QV=function(a){a?d7(2):(d7(1),qQa(this,8))};
g.k.SB=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.Bi;a.L=!1;return a};
g.k.isActive=function(){return!!this.Hf&&this.Hf.isActive(this)};
g.k.lj=function(a){var b=c7;b.dispatchEvent(new fQa(b,a))};
g.k.Tv=function(){return!(!g.fe||g.$d(10))};
g.k=rQa.prototype;g.k.KH=function(){};
g.k.JH=function(){};
g.k.IH=function(){};
g.k.FB=function(){};
g.k.sI=function(){return{}};
g.k.isActive=function(){return!0};g.k=sQa.prototype;g.k.isEmpty=function(){return 0===this.i.length&&0===this.l.length};
g.k.clear=function(){this.i=[];this.l=[]};
g.k.contains=function(a){return g.ib(this.i,a)||g.ib(this.l,a)};
g.k.remove=function(a){var b=this.i;var c=(0,g.pJa)(b,a);0<=c?(g.lb(b,c),b=!0):b=!1;return b||g.nb(this.l,a)};
g.k.Rg=function(){for(var a=[],b=this.i.length-1;0<=b;--b)a.push(this.i[b]);var c=this.l.length;for(b=0;b<c;++b)a.push(this.l[b]);return a};g.Sa(y7,g.E);g.k=y7.prototype;g.k.CU=function(){this.Mf=Math.min(3E5,2*this.Mf);this.u();this.l&&this.start()};
g.k.start=function(){var a=this.Mf+15E3*Math.random();g.Fq(this.i,a);this.l=Date.now()+a};
g.k.stop=function(){this.i.stop();this.l=0};
g.k.isActive=function(){return this.i.isActive()};
g.k.reset=function(){this.i.stop();this.Mf=5E3};g.Sa(z7,rQa);g.k=z7.prototype;g.k.subscribe=function(a,b,c){return this.u.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.u.unsubscribe(a,b,c)};
g.k.Rf=function(a){return this.u.Rf(a)};
g.k.X=function(a,b){return this.u.X.apply(this.u,arguments)};
g.k.dispose=function(){this.ea||(this.ea=!0,g.ff(this.u),vQa(this),g.ff(this.l),this.l=null,this.Y=function(){return""})};
g.k.isDisposed=function(){return this.ea};
g.k.connect=function(a,b,c){if(!this.i||2!=this.i.getState()){this.V="";this.l.stop();this.C=a||null;this.B=b||0;a=this.va+"/test";b=this.va+"/bind";var d=new r7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.ya),e=this.i;e&&(e.Hf=null);d.Hf=this;this.i=d;A7(this);if(this.i){d=g.N("ID_TOKEN");var f=this.i.Pj||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.i.Pj=f}e?(3!=e.getState()&&0==lQa(e)||e.getState(),this.i.connect(a,b,this.I,e.l,e.Nr)):c?this.i.connect(a,
b,this.I,c.sessionId,c.arrayId):this.i.connect(a,b,this.I)}};
g.k.sendMessage=function(a,b){a={_sc:a};b&&g.Yb(a,b);this.l.isActive()||2==(this.i?this.i.getState():0)?this.J.push(a):B7(this)&&(A7(this),kQa(this.i,a))};
g.k.KH=function(){this.l.reset();this.C=null;this.B=0;if(this.J.length){var a=this.J;this.J=[];for(var b=0,c=a.length;b<c;++b)kQa(this.i,a[b])}this.X("handlerOpened")};
g.k.IH=function(a){var b=2==a&&401==this.i.Qj;4==a||b||this.l.start();this.X("handlerError",a,b)};
g.k.FB=function(a){if(!this.l.isActive())this.X("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.J.push(d)}};
g.k.sI=function(){var a={v:2};this.V&&(a.gsessionid=this.V);0!=this.B&&(a.ui=""+this.B);0!=this.L&&(a.ui=""+this.L);this.C&&g.Yb(a,this.C);return a};
g.k.JH=function(a){"S"==a[0]?this.V=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),iQa(this.i)):this.X("handlerMessage",new tQa(a[0],a[1]))};
g.k.xz=function(a){(this.I.loungeIdToken=a)||this.l.stop();if(this.Aa&&this.i){var b=this.i.Pj||{};a?b["X-YouTube-LoungeId-Token"]=a:delete b["X-YouTube-LoungeId-Token"];this.i.Pj=b}};
g.k.tV=function(){this.l.isActive();0==lQa(this.i)&&this.connect(this.C,this.B)};C7.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
C7.prototype.u=function(a,b){a(Error("Request error: "+b.status))};
C7.prototype.C=function(a){a(Error("request timed out"))};var CQa=Date.now(),F7=null,I7=Array(50),H7=-1,J7=!1;g.Sa(K7,g.P);K7.prototype.yh=function(){return this.screens};
K7.prototype.contains=function(a){return!!M6(this.screens,a)};
K7.prototype.get=function(a){return a?N6(this.screens,a):null};
K7.prototype.info=function(a){G7(this.I,a)};g.v(L7,g.P);g.k=L7.prototype;g.k.start=function(){!this.i&&isNaN(this.Ib)&&this.bL()};
g.k.stop=function(){this.i&&(this.i.abort(),this.i=null);isNaN(this.Ib)||(g.Ws(this.Ib),this.Ib=NaN)};
g.k.xa=function(){this.stop();g.P.prototype.xa.call(this)};
g.k.bL=function(){this.Ib=NaN;this.i=g.at(D7(this.u,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:this.J},timeout:5E3,onSuccess:(0,g.C)(this.BO,this),onError:(0,g.C)(this.AO,this),onTimeout:(0,g.C)(this.CO,this)})};
g.k.BO=function(a,b){this.i=null;a=b.screen||{};a.dialId=this.B;a.name=this.I;b=-1;this.C&&a.shortLivedLoungeToken&&a.shortLivedLoungeToken.value&&a.shortLivedLoungeToken.refreshIntervalMs&&(a.screenIdType="shortLived",a.loungeToken=a.shortLivedLoungeToken.value,b=a.shortLivedLoungeToken.refreshIntervalMs);this.X("pairingComplete",new H6(a),b)};
g.k.AO=function(a){this.i=null;a.status&&404==a.status?this.l>=WRa.length?this.X("pairingFailed",Error("DIAL polling timed out")):(a=WRa[this.l],this.Ib=g.Us((0,g.C)(this.bL,this),a),this.l++):this.X("pairingFailed",Error("Server error "+a.status))};
g.k.CO=function(){this.i=null;this.X("pairingFailed",Error("Server not responding"))};
var WRa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Sa(N7,K7);g.k=N7.prototype;g.k.start=function(){M7(this)&&this.X("screenChange");!g.gz("yt-remote-lounge-token-expiration")&&GQa(this);g.Ws(this.i);this.i=g.Us((0,g.C)(this.start,this),1E4)};
g.k.add=function(a,b){M7(this);DQa(this,a);O7(this,!1);this.X("screenChange");b(a);a.token||GQa(this)};
g.k.remove=function(a,b){var c=M7(this);FQa(this,a)&&(O7(this,!1),c=!0);b(a);c&&this.X("screenChange")};
g.k.Sz=function(a,b,c,d){var e=M7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,O7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.X("screenChange")};
g.k.xa=function(){g.Ws(this.i);N7.Td.xa.call(this)};
g.k.rQ=function(a){M7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}O7(this,!b);b&&G7(this.I,"Missed "+b+" lounge tokens.")};
g.k.qQ=function(a){G7(this.I,"Requesting lounge tokens failed: "+a)};g.v(Q7,g.P);g.k=Q7.prototype;g.k.start=function(){var a=parseInt(g.gz("yt-remote-fast-check-period")||"0",10);(this.B=g.Ra()-144E5<a?0:a)?T7(this):(this.B=g.Ra()+3E5,g.fz("yt-remote-fast-check-period",this.B),this.mE())};
g.k.isEmpty=function(){return g.Rb(this.i)};
g.k.update=function(){P7("Updating availability on schedule.");var a=this.I(),b=g.Eb(this.i,function(c,d){return c&&!!N6(a,d)},this);
S7(this,b)};
g.k.xa=function(){g.Ws(this.u);this.u=NaN;this.l&&(this.l.abort(),this.l=null);g.P.prototype.xa.call(this)};
g.k.mE=function(){g.Ws(this.u);this.u=NaN;this.l&&this.l.abort();var a=IQa(this);if(D6(a)){var b=D7(this.C,"/pairing/get_screen_availability");this.l=E7(this.C,b,{lounge_token:g.Mb(a).join(",")},(0,g.C)(this.iU,this,a),(0,g.C)(this.hU,this))}else S7(this,{}),T7(this)};
g.k.iU=function(a,b){this.l=null;var c=g.Mb(IQa(this));if(g.zb(c,g.Mb(a))){b=b.screens||[];c={};for(var d=0,e=b.length;d<e;++d)c[a[b[d].loungeToken]]="online"==b[d].status;S7(this,c);T7(this)}else this.Ud("Changing Screen set during request."),this.mE()};
g.k.hU=function(a){this.Ud("Screen availability failed: "+a);this.l=null;T7(this)};
g.k.Ud=function(a){G7("OnlineScreenService",a)};g.Sa(U7,K7);g.k=U7.prototype;g.k.start=function(){this.l.start();this.i.start();this.screens.length&&(this.X("screenChange"),this.i.isEmpty()||this.X("onlineScreenChange"))};
g.k.add=function(a,b,c){this.l.add(a,b,c)};
g.k.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.k.Sz=function(a,b,c,d){this.l.contains(a)?this.l.Sz(a,b,c,d):(a="Updating name of unknown screen: "+a.name,G7(this.I,a),d(Error(a)))};
g.k.yh=function(a){return a?this.screens:g.pb(this.screens,g.Ro(this.u,function(b){return!this.contains(b)},this))};
g.k.kG=function(){return g.Ro(this.yh(!0),function(a){return!!this.i.i[a.id]},this)};
g.k.lG=function(a,b,c,d,e,f){var h=this;this.info("getDialScreenByPairingCode "+a+" / "+b);var l=new L7(this.B,a,b,c,d);l.subscribe("pairingComplete",function(m,n){g.ff(l);e(V7(h,m),n)});
l.subscribe("pairingFailed",function(m){g.ff(l);f(m)});
l.start();return(0,g.C)(l.stop,l)};
g.k.DO=function(a,b,c,d){g.at(D7(this.B,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:a},timeout:5E3,onSuccess:(0,g.C)(function(e,f){e=new H6(f.screen||{});if(!e.name||MQa(this,e.name)){a:{f=e.name;for(var h=2,l=b(f,h);MQa(this,l);){h++;if(20<h)break a;l=b(f,h)}f=l}e.name=f}c(V7(this,e))},this),
onError:(0,g.C)(function(e){d(Error("pairing request failed: "+e.status))},this),
onTimeout:(0,g.C)(function(){d(Error("pairing request timed out."))},this)})};
g.k.xa=function(){g.ff(this.l);g.ff(this.i);U7.Td.xa.call(this)};
g.k.AQ=function(){OQa(this);this.X("screenChange");this.i.update()};
U7.prototype.dispose=U7.prototype.dispose;g.Sa(X7,g.P);g.k=X7.prototype;g.k.getScreen=function(){return this.B};
g.k.gg=function(a){this.isDisposed()||(a&&Z7(this,""+a),this.B=null,this.X("sessionScreen",null))};
g.k.info=function(a){G7(this.Aa,a)};
g.k.mG=function(){return null};
g.k.zE=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.C)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.C)(function(){Z7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.xa=function(){this.zE("");X7.Td.xa.call(this)};g.v($7,X7);g.k=$7.prototype;g.k.yE=function(a){if(this.l){if(this.l==a)return;Z7(this,"Overriding cast session with new session object");XQa(this);this.va=!1;this.V="unknown";this.l.removeUpdateListener(this.Y);this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.ya)}this.l=a;this.l.addUpdateListener(this.Y);this.l.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.ya);TQa(this,"getMdxSessionStatus")};
g.k.Or=function(a){this.info("launchWithParams no-op for Cast: "+g.Lh(a))};
g.k.stop=function(){this.l?this.l.stop((0,g.C)(function(){this.gg()},this),(0,g.C)(function(){this.gg(Error("Failed to stop receiver app."))},this)):this.gg(Error("Stopping cast device without session."))};
g.k.zE=function(){};
g.k.xa=function(){this.info("disposeInternal");XQa(this);this.l&&(this.l.removeUpdateListener(this.Y),this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.ya));this.l=null;X7.prototype.xa.call(this)};
g.k.VU=function(a,b){if(!this.isDisposed())if(b)if(b=E6(b),g.Ma(b))switch(a=""+b.type,b=b.data||{},this.info("onYoutubeMessage_: "+a+" "+g.Lh(b)),a){case "mdxSessionStatus":RQa(this,b);break;case "loungeToken":UQa(this,b);break;default:Z7(this,"Unknown youtube message: "+a)}else Z7(this,"Unable to parse message.");else Z7(this,"No data in message.")};
g.k.HI=function(a,b,c,d){g.Ws(this.L);this.L=0;LQa(this.u,this.i.label,a,this.i.friendlyName,(0,g.C)(function(e){e?b(e):0<=d?(Z7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),this.L=g.Us((0,g.C)(this.HI,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.mG=function(){return this.l};
g.k.EO=function(a){this.isDisposed()||a||(Z7(this,"Cast session died."),this.gg())};g.v(c8,X7);g.k=c8.prototype;g.k.yE=function(a){this.l=a;this.l.addUpdateListener(this.Da)};
g.k.Or=function(a){this.Ja=a;this.ea()};
g.k.stop=function(){dRa(this);this.l?this.l.stop((0,g.C)(this.gg,this,null),(0,g.C)(this.gg,this,"Failed to stop DIAL device.")):this.gg()};
g.k.xa=function(){dRa(this);this.l&&this.l.removeUpdateListener(this.Da);this.l=null;X7.prototype.xa.call(this)};
g.k.FO=function(a){this.isDisposed()||a||(Z7(this,"DIAL session died."),this.C(),this.C=g.Ia,this.gg())};g.v(g8,X7);g8.prototype.stop=function(){this.gg()};
g8.prototype.yE=function(){};
g8.prototype.Or=function(){g.Ws(this.l);this.l=NaN;var a=N6(this.u.yh(),this.i.label);a?Y7(this,a):this.gg(Error("No such screen"))};
g8.prototype.xa=function(){g.Ws(this.l);this.l=NaN;X7.prototype.xa.call(this)};g.v(h8,g.P);g.k=h8.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.J);this.L||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED;a=a||this.V?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;var e=(0,g.C)(this.QT,this);c=new chrome.cast.ApiConfig(c,(0,g.C)(this.OK,this),e,d,a);c.customDialLaunchCallback=(0,g.C)(this.AS,this);chrome.cast.initialize(c,(0,g.C)(function(){this.isDisposed()||
(chrome.cast.addReceiverActionListener(this.C),zQa(),this.l.subscribe("onlineScreenChange",(0,g.C)(this.nG,this)),this.u=fRa(this),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.C)(function(f){this.Ud("Failed to set initial custom receivers: "+g.Lh(f))},this)),this.X("yt-remote-cast2-availability-change",j8(this)),b(!0))},this),(0,g.C)(function(f){this.Ud("Failed to initialize API: "+g.Lh(f));
b(!1)},this))};
g.k.zV=function(a,b){i8("Setting connected screen ID: "+a+" -> "+b);if(this.i){var c=this.i.getScreen();if(!a||c&&c.id!=a)i8("Unsetting old screen status: "+this.i.i.friendlyName),k8(this,null)}if(a&&b){if(!this.i){c=N6(this.l.yh(),a);if(!c){i8("setConnectedScreenStatus: Unknown screen.");return}if("shortLived"==c.idType){i8("setConnectedScreenStatus: Screen with id type to be short lived.");return}a=eRa(this,c);a||(i8("setConnectedScreenStatus: Connected receiver not custom..."),a=new chrome.cast.Receiver(c.uuid?
c.uuid:c.id,c.name),a.receiverType=chrome.cast.ReceiverType.CUSTOM,this.u.push(a),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.C)(function(d){this.Ud("Failed to set initial custom receivers: "+g.Lh(d))},this)));
i8("setConnectedScreenStatus: new active receiver: "+a.friendlyName);k8(this,new g8(this.l,a),!0)}this.i.zE(b)}else i8("setConnectedScreenStatus: no screen.")};
g.k.AV=function(a){this.isDisposed()?this.Ud("Setting connection data on disposed cast v2"):this.i?this.i.Or(a):this.Ud("Setting connection data without a session")};
g.k.HO=function(){this.isDisposed()?this.Ud("Stopping session on disposed cast v2"):this.i?(this.i.stop(),k8(this,null)):i8("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.C)(this.OK,this),(0,g.C)(this.lU,this))};
g.k.xa=function(){this.l.unsubscribe("onlineScreenChange",(0,g.C)(this.nG,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.C);var a=wQa,b=g.Ha("yt.mdx.remote.debug.handlers_");g.nb(b||[],a);g.ff(this.i);g.P.prototype.xa.call(this)};
g.k.Ud=function(a){G7("Controller",a)};
g.k.QK=function(a,b){this.i==a&&(b||k8(this,null),this.X("yt-remote-cast2-session-change",b))};
g.k.NT=function(a,b){if(!this.isDisposed())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),i8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.i)if(this.i.i.label!=a.label)i8("onReceiverAction_: Stopping active receiver: "+this.i.i.friendlyName),this.i.stop();else{i8("onReceiverAction_: Casting to active receiver.");this.i.getScreen()&&this.X("yt-remote-cast2-session-change",this.i.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:k8(this,
new g8(this.l,a));break;case chrome.cast.ReceiverType.DIAL:k8(this,new c8(this.l,a,this.B,this.config_));break;case chrome.cast.ReceiverType.CAST:k8(this,new $7(this.l,a,this.config_));break;default:this.Ud("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.i&&this.i.i.label==a.label?this.i.stop():this.Ud("Stopping receiver w/o session: "+a.friendlyName)}else this.Ud("onReceiverAction_ called without receiver.")};
g.k.AS=function(a){if(this.isDisposed())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Ud("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.i?this.i.i:null;if(!c||c.label!=b.label)return this.Ud("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.i.getScreen())return i8("Reselecting dial screen."),
this.X("yt-remote-cast2-session-change",this.i.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Ud('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);k8(this,new c8(this.l,b,this.B,this.config_))}b=this.i;b.L=a;b.L.appState==chrome.cast.DialAppState.RUNNING?(a=b.L.extraData||{},c=a.screenId||null,d8(b)&&a.loungeToken?a.loungeTokenRefreshIntervalMs?a=aRa(b,{name:b.i.friendlyName,screenId:a.screenId,loungeToken:a.loungeToken,dialId:b.L.receiver.label,
screenIdType:"shortLived"},a.loungeTokenRefreshIntervalMs):(g.ds(Error("No loungeTokenRefreshIntervalMs presents in additionalData: "+JSON.stringify(a)+".")),a=bRa(b,c)):a=bRa(b,c)):a=f8(b);return a};
g.k.OK=function(a){if(!this.isDisposed()){i8("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.i)if(b.receiverType==chrome.cast.ReceiverType.CAST)i8("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),k8(this,new $7(this.l,b,this.config_),!0);else{this.Ud("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.i.i,d=N6(this.l.yh(),c.label);
d&&I6(d,b.label)&&c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(i8("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.ff(this.i),this.i=new $7(this.l,b,this.config_),this.i.subscribe("sessionScreen",(0,g.C)(this.QK,this,this.i)),this.i.Or(null));this.i.yE(a)}}};
g.k.GO=function(){return this.i?this.i.mG():null};
g.k.lU=function(a){this.isDisposed()||(this.Ud("Failed to estabilish a session: "+g.Lh(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&k8(this,null))};
g.k.QT=function(a){i8("Receiver availability updated: "+a);if(!this.isDisposed()){var b=j8(this);this.I=a==chrome.cast.ReceiverAvailability.AVAILABLE;j8(this)!=b&&this.X("yt-remote-cast2-availability-change",j8(this))}};
g.k.nG=function(){this.isDisposed()||(this.u=fRa(this),i8("Updating custom receivers: "+g.Lh(this.u)),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.C)(function(){this.Ud("Failed to set custom receivers.")},this)),this.X("yt-remote-cast2-availability-change",j8(this)))};
h8.prototype.setLaunchParams=h8.prototype.AV;h8.prototype.setConnectedScreenStatus=h8.prototype.zV;h8.prototype.stopSession=h8.prototype.HO;h8.prototype.getCastSession=h8.prototype.GO;h8.prototype.requestSession=h8.prototype.requestSession;h8.prototype.init=h8.prototype.init;h8.prototype.dispose=h8.prototype.dispose;var q8=[];g.k=v8.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";w8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.trackData=a.trackData,this.jk=a.hasPrevious,this.hasNext=a.hasNext,this.J=a.playerTime,this.I=a.playerTimeAt,this.B=a.seekableStart,this.i=a.seekableEnd,this.C=a.duration,this.L=a.loadedTime,this.u=a.liveIngestionTime,this.l=
!isNaN(this.u))};
g.k.zc=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.vj=function(a){this.C=isNaN(a)?0:a};
g.k.getDuration=function(){return this.l?this.C+x8(this):this.C};
g.k.clone=function(){return new v8(B8(this))};g.v(D8,g.P);g.k=D8.prototype;g.k.getState=function(){return this.Oa};
g.k.play=function(){F8(this)?(this.i?this.i.play(null,g.Ia,K8(this,"play")):J8(this,"play"),I8(this,1,z8(E8(this))),this.X("remotePlayerChange")):G8(this,this.play)};
g.k.pause=function(){F8(this)?(this.i?this.i.pause(null,g.Ia,K8(this,"pause")):J8(this,"pause"),I8(this,2,z8(E8(this))),this.X("remotePlayerChange")):G8(this,this.pause)};
g.k.seekTo=function(a){if(F8(this)){if(this.i){var b=E8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.zc()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ia,K8(this,"seekTo",{newTime:a}))}else J8(this,"seekTo",{newTime:a});I8(this,3,a);this.X("remotePlayerChange")}else G8(this,g.Pa(this.seekTo,a))};
g.k.stop=function(){if(F8(this)){this.i?this.i.stop(null,g.Ia,K8(this,"stopVideo")):J8(this,"stopVideo");var a=E8(this);a.index=-1;a.videoId="";w8(a);H8(this,a);this.X("remotePlayerChange")}else G8(this,this.stop)};
g.k.setVolume=function(a,b){if(F8(this)){var c=E8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.C)(function(){G7("CP","set receiver volume: "+d)},this),(0,g.C)(function(){this.Ud("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.C)(function(){G7("CP","set receiver muted: "+b)},this),(0,g.C)(function(){this.Ud("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);J8(this,"setVolume",e)}c.muted=b;c.volume=a;H8(this,c)}else G8(this,g.Pa(this.setVolume,a,b))};
g.k.oG=function(a,b){if(F8(this)){var c=E8(this);a={videoId:a};b&&(c.trackData={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},a.style=g.Lh(b.style),g.Yb(a,c.trackData));J8(this,"setSubtitlesTrack",a);H8(this,c)}else G8(this,g.Pa(this.oG,a,b))};
g.k.setAudioTrack=function(a,b){F8(this)?(b=b.getLanguageInfo().getId(),J8(this,"setAudioTrack",{videoId:a,audioTrackId:b}),a=E8(this),a.audioTrackId=b,H8(this,a)):G8(this,g.Pa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){d=void 0===d?null:d;e=void 0===e?null:e;f=void 0===f?null:f;h=void 0===h?null:h;var l=E8(this),m={videoId:a};void 0!==c&&(m.currentIndex=c);A8(l,a,c||0);void 0!==b&&(y8(l,b),m.currentTime=b);d&&(m.listId=d);e&&(m.playerParams=e);f&&(m.clickTrackingParams=f);h&&(m.locationInfo=g.Lh(h));J8(this,"setPlaylist",m);d||H8(this,l)};
g.k.bz=function(a,b){if(F8(this)){if(a&&b){var c=E8(this);A8(c,a,b);H8(this,c)}J8(this,"previous")}else G8(this,g.Pa(this.bz,a,b))};
g.k.nextVideo=function(a,b){if(F8(this)){if(a&&b){var c=E8(this);A8(c,a,b);H8(this,c)}J8(this,"next")}else G8(this,g.Pa(this.nextVideo,a,b))};
g.k.bI=function(){F8(this)?J8(this,"dismissAutoplay"):G8(this,this.bI)};
g.k.dispose=function(){if(3!=this.Oa){var a=this.Oa;this.Oa=3;this.X("proxyStateChange",a,this.Oa)}g.P.prototype.dispose.call(this)};
g.k.xa=function(){rRa(this);this.u=null;this.B.clear();C8(this,null);g.P.prototype.xa.call(this)};
g.k.BE=function(a){if((a!=this.Oa||2==a)&&3!=this.Oa&&0!=a){var b=this.Oa;this.Oa=a;this.X("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,0===b.i.length&&(b.i=b.l,b.i.reverse(),b.l=[]),a.i.pop().apply(this);else 3==a&&this.dispose()}};
g.k.JT=function(a,b){this.X(a,b)};
g.k.lS=function(a){if(!a)this.fv(null),C8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=E8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)G7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,H8(this,b)}};
g.k.fv=function(a){G7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.J);if(this.i=a)this.i.addUpdateListener(this.J),sRa(this),this.X("remotePlayerChange")};
g.k.kS=function(a){a?(sRa(this),this.X("remotePlayerChange")):this.fv(null)};
g.k.UE=function(){J8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.sS=function(){var a=oRa();a&&C8(this,a)};
g.k.Ud=function(a){G7("CP",a)};g.v(L8,g.P);g.k=L8.prototype;
g.k.connect=function(a,b,c){c=void 0===c?!1:c;if(b){var d=b.listId,e=b.videoId,f=b.videoIds,h=b.playerParams,l=b.clickTrackingParams,m=b.index,n={videoId:e},p=b.currentTime,r=b.locationInfo;b=b.loopMode;void 0!==p&&(n.currentTime=5>=p?0:p);h&&(n.playerParams=h);r&&(n.locationInfo=r);l&&(n.clickTrackingParams=l);d&&(n.listId=d);f&&0<f.length&&(n.videoIds=f.join(","));void 0!==m&&(n.currentIndex=m);c&&(n.loopMode=b||"LOOP_MODE_OFF");d&&(this.kc.listId=d);this.kc.videoId=e;this.kc.index=m||0;this.kc.state=
3;y8(this.kc,p);this.B="UNSUPPORTED";c=c?"setInitialState":"setPlaylist";M8("Connecting with "+c+" and params: "+g.Lh(n));this.i.connect({method:c,params:g.Lh(n)},a,BPa())}else M8("Connecting without params"),this.i.connect({},a,BPa());uRa(this)};
g.k.xz=function(a){this.i.xz(a)};
g.k.dispose=function(){this.isDisposed()||(this.X("beforeDispose"),N8(this,3));g.P.prototype.dispose.call(this)};
g.k.xa=function(){O8(this);Q8(this);P8(this);g.Ws(this.J);this.J=NaN;g.Ws(this.L);this.L=NaN;this.u=null;g.au(this.V);this.V.length=0;this.i.dispose();g.P.prototype.xa.call(this);this.B=this.I=this.l=this.kc=this.i=null};
g.k.mQ=function(){this.jr(2)};
g.k.pS=function(){M8("Channel opened");this.va&&(this.va=!1,P8(this),this.Y=g.Us((0,g.C)(function(){M8("Timing out waiting for a screen.");this.jr(1)},this),15E3));
FPa(uQa(this.i),this.Da)};
g.k.mS=function(){M8("Channel closed");isNaN(this.C)?S6(!0):S6();this.dispose()};
g.k.nS=function(a,b){S6();isNaN(this.yu())?(b&&"shortLived"==this.ya&&this.X("browserChannelAuthError",a),M8("Channel error: "+a+" without reconnection"),this.dispose()):(this.va=!0,M8("Channel error: "+a+" with reconnection in "+this.yu()+" ms"),N8(this,2))};
g.k.lJ=function(a){if(!this.l||0===this.l.length)return!1;for(var b=g.q(this.l),c=b.next();!c.done;c=b.next())if(!c.value.capabilities.has(a))return!1;return!0};
g.k.oS=function(a){a.params?M8("Received: action="+a.action+", params="+g.Lh(a.params)):M8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=E6(a.params.devices);this.l=g.Re(a,function(c){return new G6(c)});
a=!!g.eb(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
xRa(this,a);a=this.lJ("mlm");this.X("multiStateLoopEnabled",a);break;case "loungeScreenDisconnected":g.ob(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
xRa(this,!1);break;case "remoteConnected":var b=new G6(E6(a.params.device));g.eb(this.l,function(c){return b?c.id==b.id:!1})||oPa(this.l,b);
break;case "remoteDisconnected":b=new G6(E6(a.params.device));g.ob(this.l,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":zRa(this,a);break;case "nowPlaying":BRa(this,a);break;case "onStateChange":ARa(this,a);break;case "onAdStateChange":CRa(this,a);break;case "onVolumeChanged":DRa(this,a);break;case "onSubtitlesTrackChanged":yRa(this,a);break;case "nowAutoplaying":ERa(this,a);break;case "autoplayDismissed":this.X("autoplayDismissed");break;case "autoplayUpNext":this.I=a.params.videoId||null;this.X("autoplayUpNext",this.I);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.X("autoplayModeChange",this.B);"DISABLED"==this.B&&this.X("autoplayDismissed");break;case "onHasPreviousNextChanged":FRa(this,a);break;case "requestAssistedSignIn":this.X("assistedSignInRequested",a.params.authCode);break;case "onLoopModeChanged":this.X("loopModeChange",a.params.loopMode);break;default:M8("Unrecognized action: "+a.action)}};
g.k.nV=function(){if(this.u){var a=this.u;this.u=null;this.kc.videoId!=a&&R8(this,"getNowPlaying")}};
g.k.hQ=function(){var a=3;this.isDisposed()||(a=0,isNaN(this.yu())?B7(this.i)&&isNaN(this.C)&&(a=1):a=2);return a};
g.k.jr=function(a){M8("Disconnecting with "+a);O8(this);this.X("beforeDisconnect",a);1==a&&S6();vQa(this.i,a);this.dispose()};
g.k.fQ=function(){var a=this.kc;this.u&&(a=this.kc.clone(),A8(a,this.u,a.index));return B8(a)};
g.k.BV=function(a){var b=new v8(a);b.videoId&&b.videoId!=this.kc.videoId&&(this.u=b.videoId,g.Ws(this.J),this.J=g.Us((0,g.C)(this.nV,this),5E3));var c=[];this.kc.listId==b.listId&&this.kc.videoId==b.videoId&&this.kc.index==b.index||c.push("remoteQueueChange");this.kc.playerState==b.playerState&&this.kc.volume==b.volume&&this.kc.muted==b.muted&&z8(this.kc)==z8(b)&&g.Lh(this.kc.trackData)==g.Lh(b.trackData)||c.push("remotePlayerChange");this.kc.reset(a);g.Bb(c,function(d){this.X(d)},this)};
g.k.GI=function(){var a=this.i.I.id,b=g.eb(this.l,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.yu=function(){var a=this.i;return a.l.isActive()?a.l.l-Date.now():NaN};
g.k.cQ=function(){return this.B||"UNSUPPORTED"};
g.k.dQ=function(){return this.I||""};
g.k.IO=function(){if(!isNaN(this.yu())){var a=this.i.l;g.Gq(a.i);a.start()}};
g.k.yV=function(a,b){R8(this,a,b);wRa(this)};
g.k.pG=function(){var a=g.mt("SID","")||"",b=g.mt("SAPISID","")||"",c=g.mt("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.ce(g.Xa(a),2);b=g.ce(g.Xa(b),2);c=g.ce(g.Xa(c),2);return g.ce(g.Xa(a+","+b+","+c),2)};
L8.prototype.subscribe=L8.prototype.subscribe;L8.prototype.unsubscribeByKey=L8.prototype.Rf;L8.prototype.getProxyState=L8.prototype.hQ;L8.prototype.disconnect=L8.prototype.jr;L8.prototype.getPlayerContextData=L8.prototype.fQ;L8.prototype.setPlayerContextData=L8.prototype.BV;L8.prototype.getOtherConnectedRemoteId=L8.prototype.GI;L8.prototype.getReconnectTimeout=L8.prototype.yu;L8.prototype.getAutoplayMode=L8.prototype.cQ;L8.prototype.getAutoplayVideoId=L8.prototype.dQ;L8.prototype.reconnect=L8.prototype.IO;
L8.prototype.sendMessage=L8.prototype.yV;L8.prototype.getXsrfToken=L8.prototype.pG;L8.prototype.isCapabilitySupportedOnConnectedDevices=L8.prototype.lJ;g.v(S8,K7);g.k=S8.prototype;g.k.yh=function(a){return this.Ie.$_gs(a)};
g.k.contains=function(a){return!!this.Ie.$_c(a)};
g.k.get=function(a){return this.Ie.$_g(a)};
g.k.start=function(){this.Ie.$_st()};
g.k.add=function(a,b,c){this.Ie.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Ie.$_r(a,b,c)};
g.k.Sz=function(a,b,c,d){this.Ie.$_un(a,b,c,d)};
g.k.xa=function(){for(var a=0,b=this.i.length;a<b;++a)this.Ie.$_ubk(this.i[a]);this.i.length=0;this.Ie=null;K7.prototype.xa.call(this)};
g.k.JO=function(){this.X("screenChange")};
g.k.rT=function(){this.X("onlineScreenChange")};
U7.prototype.$_st=U7.prototype.start;U7.prototype.$_gspc=U7.prototype.DO;U7.prototype.$_gsppc=U7.prototype.lG;U7.prototype.$_c=U7.prototype.contains;U7.prototype.$_g=U7.prototype.get;U7.prototype.$_a=U7.prototype.add;U7.prototype.$_un=U7.prototype.Sz;U7.prototype.$_r=U7.prototype.remove;U7.prototype.$_gs=U7.prototype.yh;U7.prototype.$_gos=U7.prototype.kG;U7.prototype.$_s=U7.prototype.subscribe;U7.prototype.$_ubk=U7.prototype.Rf;var e9=null,k9=!1,T8=null,U8=null,j9=null,Y8=[];g.v(l9,g.E);g.k=l9.prototype;g.k.xa=function(){g.E.prototype.xa.call(this);this.i.stop();this.u.stop();this.L.stop();this.Y();var a=this.Qb;a.unsubscribe("proxyStateChange",this.MK,this);a.unsubscribe("remotePlayerChange",this.wv,this);a.unsubscribe("remoteQueueChange",this.Sy,this);a.unsubscribe("previousNextChange",this.JK,this);a.unsubscribe("nowAutoplaying",this.DK,this);a.unsubscribe("autoplayDismissed",this.gK,this);this.Qb=this.l=null};
g.k.dj=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.Qb.Oa)if(m9(this)){if(!E8(this.Qb).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":E8(this.Qb).zc()?this.Qb.pause():this.Qb.play();break;case "control_play":this.Qb.play();break;case "control_pause":this.Qb.pause();break;case "control_seek":this.J.jG(c[0],c[1]);break;case "control_subtitles_set_track":n9(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.G.getCurrentTime();o9(this,0===c?void 0:c);break;case "control_seek":o9(this,c[0]);break;case "control_subtitles_set_track":n9(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.iS=function(a){this.L.xO(a)};
g.k.iW=function(a){this.dj("control_subtitles_set_track",g.Rb(a)?null:a)};
g.k.WL=function(){var a=this.G.getOption("captions","track");g.Rb(a)||n9(this,a)};
g.k.Sb=function(a){this.l.Sb(a,this.G.getVideoData().lengthSeconds)};
g.k.aT=function(){g.Rb(this.B)||QRa(this,this.B);this.C=!1};
g.k.MK=function(a,b){this.u.stop();2===b&&this.QL()};
g.k.wv=function(){if(m9(this)){this.i.stop();var a=E8(this.Qb);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.l.jf=1;break;case 1082:case 1083:this.l.jf=0;break;default:this.l.jf=-1}switch(a.playerState){case 1081:case 1:this.Lb(new g.FK(8));this.PL();break;case 1085:case 3:this.Lb(new g.FK(9));break;case 1083:case 0:this.Lb(new g.FK(2));this.J.stop();this.Sb(this.G.getVideoData().lengthSeconds);break;case 1084:this.Lb(new g.FK(4));break;case 2:this.Lb(new g.FK(4));this.Sb(z8(a));
break;case -1:this.Lb(new g.FK(64));break;case -1E3:this.Lb(new g.FK(128,{errorCode:"mdx.remoteerror",errorMessage:"Este v\u00eddeo no se puede reproducir de forma remota."}))}a=E8(this.Qb).trackData;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,QRa(this,a));a=E8(this.Qb);-1===a.volume||Math.round(this.G.getVolume())===a.volume&&this.G.isMuted()===a.muted||this.V.isActive()||this.xM()}else PRa(this)};
g.k.JK=function(){this.G.X("mdxpreviousnextchange")};
g.k.Sy=function(){m9(this)||PRa(this)};
g.k.DK=function(a){isNaN(a)||this.G.X("mdxnowautoplaying",a)};
g.k.gK=function(){this.G.X("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){m9(this)&&this.Qb.setAudioTrack(this.G.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===E8(this.Qb).playerState?o9(this,a):b&&this.Qb.seekTo(a)};
g.k.xM=function(){var a=this;if(m9(this)){var b=E8(this.Qb);this.events.lc(this.ea);b.muted?this.G.mute():this.G.unMute();this.G.setVolume(b.volume);this.ea=this.events.N(this.G,"onVolumeChange",function(c){ORa(a,c)})}};
g.k.PL=function(){this.i.stop();if(!this.Qb.isDisposed()){var a=E8(this.Qb);a.zc()&&this.Lb(new g.FK(8));this.Sb(z8(a));this.i.start()}};
g.k.QL=function(){this.u.stop();this.i.stop();var a=this.Qb.u.getReconnectTimeout();2==this.Qb.Oa&&!isNaN(a)&&this.u.start()};
g.k.Lb=function(a){this.u.stop();var b=this.I;if(!g.KK(b,a)){var c=g.U(a,2);c!==g.U(this.I,2)&&this.G.bq(c);this.I=a;SRa(this.l,b,a)}};g.v(p9,g.V);p9.prototype.Yc=function(){this.i.show()};
p9.prototype.Ab=function(){this.i.hide()};
p9.prototype.l=function(){g.mK("https://support.google.com/youtube/answer/7640706")};
p9.prototype.u=function(){F6("mdx-manual-pairing-popup-ok");this.Ab()};g.v(q9,g.V);q9.prototype.Yc=function(){this.i.show()};
q9.prototype.Ab=function(){this.i.hide()};
q9.prototype.l=function(){F6("mdx-privacy-popup-cancel");this.Ab()};
q9.prototype.u=function(){F6("mdx-privacy-popup-confirm");this.Ab()};g.v(r9,g.V);r9.prototype.l=function(a){RRa(this,a.state)};g.v(s9,g.uQ);s9.prototype.C=function(){var a=this.G.getOption("remote","receivers");a&&1<a.length&&!this.G.getOption("remote","quickCast")?(this.Jn=g.Cb(a,this.i,this),g.vQ(this,g.Re(a,this.i)),a=this.G.getOption("remote","currentReceiver"),a=this.i(a),this.options[a]&&this.Ph(a),this.enable(!0)):this.enable(!1)};
s9.prototype.i=function(a){return a.key};
s9.prototype.Ui=function(a){return"cast-selector-receiver"===a?"Reparto...":this.Jn[a].name};
s9.prototype.uf=function(a){g.uQ.prototype.uf.call(this,a);this.G.setOption("remote","currentReceiver",this.Jn[a]);this.yb.Ab()};g.v(t9,g.EN);g.k=t9.prototype;
g.k.create=function(){var a=this.player.T(),b=g.VF(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:g.S(a.experiments,"mdx_load_cast_api_bootstrap_script"),enableDialLoungeToken:g.S(a.experiments,"enable_dial_short_lived_lounge_token"),enableCastLoungeToken:g.S(a.experiments,"enable_cast_short_lived_lounge_token")};JRa(b,a);this.subscriptions.push(g.Iu("yt-remote-before-disconnect",this.hS,this));this.subscriptions.push(g.Iu("yt-remote-connection-change",this.RT,this));this.subscriptions.push(g.Iu("yt-remote-receiver-availability-change",
this.LK,this));this.subscriptions.push(g.Iu("yt-remote-auto-connect",this.PT,this));this.subscriptions.push(g.Iu("yt-remote-receiver-resumed",this.OT,this));this.subscriptions.push(g.Iu("mdx-privacy-popup-confirm",this.eV,this));this.subscriptions.push(g.Iu("mdx-privacy-popup-cancel",this.dV,this));this.subscriptions.push(g.Iu("mdx-manual-pairing-popup-ok",this.mR,this));this.LK()};
g.k.load=function(){this.player.cancelPlayback();g.EN.prototype.load.call(this);this.Sh=new l9(this,this.player,this.Qb);var a=(a=NRa())?a.currentTime:0;var b=i9()?new D8(c9(),void 0):null;0==a&&b&&(a=z8(E8(b)));0!==a&&this.Sb(a);SRa(this,this.ld,this.ld);this.player.Ik(6)};
g.k.unload=function(){this.player.X("mdxautoplaycanceled");this.Em=this.ij;g.jf(this.Sh,this.Qb);this.Qb=this.Sh=null;g.EN.prototype.unload.call(this);this.player.Ik(5);u9(this)};
g.k.xa=function(){g.Ju(this.subscriptions);g.EN.prototype.xa.call(this)};
g.k.yk=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.Sh.dj.apply(this.Sh,[a].concat(g.la(c)))};
g.k.getAdState=function(){return this.jf};
g.k.iQ=function(){return this.loaded?this.Sh.suggestion:null};
g.k.jk=function(){return this.Qb?E8(this.Qb).jk:!1};
g.k.hasNext=function(){return this.Qb?E8(this.Qb).hasNext:!1};
g.k.Sb=function(a,b){this.AJ=a||0;this.player.X("progresssync",a,b);this.player.Na("onVideoProgress",a)};
g.k.getCurrentTime=function(){return this.AJ};
g.k.getProgressState=function(){var a=E8(this.Qb),b=this.player.getVideoData();return{allowSeeking:g.S(this.player.T().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.gf():!a.isAdPlaying()&&this.player.gf(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.l?a.u+x8(a):a.u,isAtLiveHead:1>=(a.l?a.i+x8(a):a.i)-this.getCurrentTime(),loaded:a.L,seekableEnd:a.l?a.i+x8(a):a.i,seekableStart:0<a.B?a.B+
x8(a):a.B}};
g.k.nextVideo=function(){this.Qb&&this.Qb.nextVideo()};
g.k.bz=function(){this.Qb&&this.Qb.bz()};
g.k.hS=function(a){1===a&&(this.ZD=this.Qb?E8(this.Qb):null)};
g.k.RT=function(){var a=i9()?new D8(c9(),void 0):null;if(a){var b=this.Em;this.loaded&&this.unload();this.Qb=a;this.ZD=null;b.key!==this.ij.key&&(this.Em=b,this.load())}else g.ff(this.Qb),this.Qb=null,this.loaded&&(this.unload(),(a=this.ZD)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,z8(a)));this.player.X("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.LK=function(){var a=[this.ij],b=a.concat,c=KRa();r8()&&g.gz("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.Jn=b.call(a,c);a=d9()||this.ij;v9(this,a);this.player.Na("onMdxReceiversChange")};
g.k.PT=function(){var a=d9();v9(this,a)};
g.k.OT=function(){this.Em=d9()};
g.k.eV=function(){this.Cv=!0;u9(this);k9=!1;e9&&g9(e9,1);e9=null};
g.k.dV=function(){this.Cv=!1;u9(this);v9(this,this.ij);this.Em=this.ij;k9=!1;e9=null;this.player.playVideo()};
g.k.mR=function(){this.py=!0;u9(this);g.fz("yt-remote-manual-pairing-warning-shown",!0,2592E3);k9=!1;e9&&g9(e9,1);e9=null};
g.k.Ye=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Jn;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?t8():v9(this,b)),this.loaded?this.Em:this.ij;case "quickCast":return 2===this.Jn.length&&"cast-selector-receiver"===this.Jn[1].key?(b&&t8(),!0):!1}};
g.k.UE=function(){this.Qb.UE()};
g.k.Gi=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.PN.remote=t9;})(_yt_player);
